<div class="row clearfix">
    <div class="col-md-8 column">
        <span class="label label-primary" style="font-size: 25px">Physicians List</span>
        <br><br>
	<?php
            if ($this->physician) {
                echo "<table class='table table-striped table-hover'>";
                echo "<tr><th>Title</th><th>Name</th><th>Group Name</th><th>Action</th></tr>";
                foreach ($this->physician as $Physician) {
                    echo "<tr>";
                    echo "<td>".$Physician['title']."</td>";
                    echo "<td>".$Physician['name']."</td>";
                    echo "<td>".$Physician['group_name']."</td>";
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/user/show-profile/userId/".$Physician['id']."' class='btn btn-default'> View </a>";
                    echo "<a href='". $this->baseUrl()."/user/edit?userId=".$Physician['id']."' class='btn btn-default'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Physician/delete?id=".$Physician['id']."' class='btn btn-default'> Delete </a>";
                    echo "<a href='". $this->baseUrl()."/physicianvisit/list?id=".$Physician['id']."' class='btn btn-default'> Visits </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2> No, Physician !!</h2>";
                echo "but you can <a href='".$this->baseUrl()."/Physician/add' >Add Physician</a> ";
            }
        ?>
    </div>
</div>

