<div class="row clearfix">
    <div class="col-md-3 column"></div>
    <div class="col-md-7 column">
        <span class="label label-primary" style="font-size: 25px">Physicians Search</span>
        <br><br>
        <form class="form-horizontal" method="POST">
            <fieldset>
                <div class="form-group">
                  <label for="key" class="col-lg-2 control-label">Physician Name</label>
                  <div class="col-lg-10">      
                      <input type="text" class="form-control" id="key" name="key" placeholder="Enter search key"/>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-lg-10 col-lg-offset-2">
                      <input type="submit" value="Search" class="btn btn-primary"/>
                  </div>
                </div>            
            </fieldset>
        </form>
    <?php
       // if( $this->key ) {
        //    echo "<script>document.getElementById('key').value = '".$this->key."'; </script>";
            if ($this->physician) {
                echo "<table class='table table-striped table-hover'>";
                echo "<tr><th>Title</th><th>Name</th><th>Group Name</th><th>Action</th></tr>";
                foreach ($this->physician as $physician) {
                    echo "<tr>";
                    echo "<td>".$physician['title']."</td>";
                    echo "<td>".$physician['name']."</td>";
                    echo "<td>".$physician['group_name']."</td>";                    
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Physician/view?id=".$physician['id']."' class='btn btn-default'> View </a>";
                    echo "<a href='". $this->baseUrl()."/user/edit?userId=".$physician['id']."' class='btn btn-default'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Physician/delete?id=".$physician['id']."' class='btn btn-default'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2>Not Found !!</h2>";
            }
      //  }           
    ?>
        <br><a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
</div>
