<br /><br />
<div id="view-content">
    <h1>Physician View : </h1>
    <p>Name : <?= $this->perData['name']?></p>
    <p>Telephone : <?= $this->perData['telephone']?></p>
    <p>Mobile : <?= $this->perData['mobile']?></p>
    <p>Gender : <?= $this->perData['sex']?></p>
    <p>Title : <?= $this->phyData['title']?></p>
    <p>Email : <?= $this->userData['email']?></p>         
            
    <a href="<?= $this->baseUrl() ?>/physician/edit?id=<?= $this->perData['id'] ?>">Edit </a>
    <a href="<?= $this->baseUrl() ?>/physician/delete?id=<?= $this->perData['id'] ?>">Delete </a>
     <a href="<?= $this->baseUrl() ?>/physicianvisit/list?id=<?= $this->phyData['id'] ?>">Visits </a>
    <a href="javascript:history.back();">Back</a>
</div>