<br /><br />
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="row clearfix">
<?php
if($this->testImages)
{
    $tests = $this->testImages;
    echo "<h3>".$tests[0]["test_name"]."</h3>";
    foreach ($tests as $test)
        echo"
            <div class='col-md-2 column'>
                    <img alt='320x320' src='".$this->baseUrl()."/imgs/ResultImgs/".$this->visitID."/Tests/5-1402235452.png'>
            </div>
        ";
}
else
    echo "<h3>NO IMAGES</h3>";
//<img alt='320x320' src='".$this->baseUrl()."/imgs/ResultImgs/".$this->visitID."/Tests/".$test["title"]."'>
?>
            </div>
        </div>
    </div>
</div>
<a href="javascript:history.back();" class="btn btn-default btn-sm">Back</a>