<br />
<div id="view-content">
    <h1>Test-Results :</h1>
    <h2>Test-Results Statistics</h2>
    <ul>
        <li>
            <b>Number of Test-Results : <?= $this->testResultsStatistics['count'] ?></b>
        </li>
        <li>
            <b>Last Inserted Test-Result : --------</b>
        </li>
        <li>
            <b>Last Updated Test-Result : --------</b>
        </li>
    </ul>
  
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/Testresult/add">Add Test-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Testresult/view">View Test-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Testresult/delete">Delete Test-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Testresult/edit">Edit Test-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Testresult/search">Search Test-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Testresult/list">List Test-Results</a></li>
        
    </ul>
</div>