<br /><br />
<div id="view-content">
    <h1>Test-Result List : </h1>
	<?php
            if ($this->testResults) {
                echo "<table>";
                echo "<tr><th>Visit Request</th><th>Test</th><th>Data</th><th>Action</th></tr>";
                foreach ($this->testResults as $testResult) {
                    echo "<tr>";
                    echo "<td>".$testResult['visit_request_id']."</td>";
                    echo "<td>".$testResult['testName']."</td>";
                    if($testResult['test_data']) {
                        echo "<td>".$testResult['test_data']."</td>";
                    }
                    else {
                        echo "<td>Pending</td>";
                    }   
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Testresult/view?radId=".$testResult['test_id']."&reqId=".$testResult['visit_request_id']."'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Testresult/edit?radId=".$testResult['test_id']."&reqId=".$testResult['visit_request_id']."'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Testresult/delete?radId=".$testResult['test_id']."&reqId=".$testResult['visit_request_id']."'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2> No, Test-Results !!</h2>";
                echo "but you can <a href='".$this->baseUrl()."/Testresult/add' >Add Test-Result</a> ";
            }
        ?>
</div>