<div class="well be-component">
    <form action="search" method="GET" class="form-horizontal">
        <fieldset>
          <legend><i class="fa fa-stethoscope fa-fw"></i>Test Search </legend>
          <div class="form-group">
              <div class="col-lg-5">
                  <select name="requestId" id="requestId" class='form-control'>
                      <option value="">Choose Visit</option>
                      <?php
                          foreach ($this->requests as $request) {
                              echo "<option value='".$request['id']."'>".$request['date']."</option>";
                          }
                      ?>
                  </select>
              </div>
          </div>
          <div class="form-group">
              <div class="col-lg-5">
                  <input type="submit" value="Search" class='btn btn-primary'/>
              </div>
          </div>
        </fieldset>
    </form>
</div>
<a href="javascript:history.back();" class="btn btn-default">Back</a> 
    <?php
        if($this->requestId) {
            echo "<script>document.getElementById('requestId').value = '".$this->requestId."'; </script>";
            if ($this->testResults) {
                echo "<table>";
                echo "<tr><th>Visit Request</th><th>Test</th><th>Data</th><th>Action</th></tr>";
                foreach ($this->testResults as $testResult) {
                    echo "<tr>";
                    echo "<td>".$testResult['visit_request_id']."</td>";
                    echo "<td>".$testResult['testName']."</td>";
                    echo "<td>".$testResult['data']."</td>";
                    
                    if($testResult['data']) {
                        ?><b>Vital Data: </b><?= $testResult['data'] ?><br /><?php
                    }
                    else {
                        ?><b>Vital Data: </b>Pending<br /><?php
                    }
                    
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Testresult/view?radId=".$this->testResult['test_id']."&reqId=".$this->testResult['visit_request_id']."'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Testresult/edit?radId=".$this->testResult['test_id']."&reqId=".$this->testResult['visit_request_id']."'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Testresult/delete?radId=".$this->testResult['test_id']."&reqId=".$this->testResult['visit_request_id']."'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2>Not Found !!</h2>";
            }
        }
        
    
    ?>

