<br /><br />
<div id="view-content">
    <h1>Test-result View : </h1>
    <?php
        if($this->testResult) {
            ?>
            <b>Visit Request : </b><?= $this->testResult[0]['visit_request_id'] ?><br />
            <b>Vital : </b><?= $this->testResult[0]['testName'] ?><br />
            <?php
                if($this->testResult[0]['test_data']) {
                    ?><b>Test Data: </b><?= $this->testResult[0]['test_data'] ?><?php
                }
                else {
                    ?><b>Test Data: </b>Pending<br /><?php
                }
            ?>
            <a href="<?= $this->baseUrl() ?>/Testresult/edit?radId=<?= $this->testResult[0]['test_id'] ?>&reqId=<?= $this->testResult[0]['visit_request_id'] ?>">Edit </a>
            <a href="<?= $this->baseUrl() ?>/Testresult/delete?radId=<?= $this->testResult[0]['test_id'] ?>&reqId=<?= $this->testResult[0]['visit_request_id'] ?>">Delete </a>
            <?php
        }
        else {
            ?><h2>Not Found !!</h2><?php
        }
    ?>
    <a href="javascript:history.back();">Back</a>         
</div>