<br /><br />
<div id="view-content">
	<p>View script for controller <b>SurgeryHistory</b> and script/action name <b>edit</b></p>
</div>
<form action="" method="post">
<?php
    echo $this->surgeryHistoryForm->id.
            $this->surgeryHistoryForm->surgery.
            $this->surgeryHistoryForm->patient.
            $this->surgeryHistoryForm->physician.
            $this->surgeryHistoryForm->date.
            $this->surgeryHistoryForm->update;
?>
</form>

<?php
if($this->dataTest)
    var_dump($this->dataTest);
?>