<br />
<div id="view-content">
    <h1>Surgery-History :</h1>
    <h2>Surgery-History Statistics</h2>
    <ul>
        <li>
            <b>Number of Surgery-History : <?= $this->surgeryHistoryCount['count'] ?></b>
        </li>
        <li>
            <b>Last Inserted Surgery-History : --------</b>
        </li>
        <li>
            <b>Last Updated Surgery-History : --------</b>
        </li>
    </ul>
  
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/Surgeryhistory/add">Add Surgery-History</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Surgeryhistory/search">Delete Surgery-History</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Surgeryhistory/search">Edit Surgery-History</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Surgeryhistory/search">Search Surgery-History</a></li>
        
    </ul>
</div>