<link href="<?= $this->baseUrl() ?>/css/tableStyle.css" rel="stylesheet">
<form action="" method="post">
        <input type="text" name="patient" placeholder="Enter search patient .. "/>
        <input type="submit" value="Search"/>
</form>

 <?php
if ($this->surgeryHistory) {
    echo "<table>";
    echo "<tr><th>patient</th>";
    echo "<th>Visit Date</th>";
    echo "<th>surgery";
    echo "<th>date</th></tr>";
    foreach ($this->surgeryHistory as $surgery) {
        echo "<tr>";
        echo "<td>".$surgery["patient"]."</td>";
        echo "<td>".$surgery["physician"]."</td>";
        echo "<td>".$surgery["surgery"]."</td>";
        echo "<td>".$surgery["date"]."</td>";
        echo "<td>";
        echo "<a href='". $this->baseUrl()."/surgeryhistory/edit?id=".$surgery["sugHisID"]."'> Edit </a>";
        echo "<a href='". $this->baseUrl()."/surgeryhistory/delete?id=".$surgery["sugHisID"]."'> Delete </a>";
        echo "</td>";
        echo "</tr>";
    }
    echo "</table>";
}
else {
    echo "<h2>Not Found !!</h2>";
}   
?>