
<?php
echo "<h3>Pending</h3>";
 echo "<table>";
 echo"<tr>";
         echo "<td>Description</td>";
         echo "<td>Date</td>";
         echo "<td>Accept</td>";
            echo"</tr>";
foreach ($this->penVisits as $pen) {
    ?>
           <tr>
           <form method="GET" action="accept">
          <td><?= $pen["description"] ?></td>
          <td><?= $pen["date"] ?></td>
          <td><input type="date" name="created_date" min="<?= $pen["date"] ?>"></td>
           <input type="hidden" value="<?= $pen['id'] ?>" name="vid">
           <input type="hidden" value="<?= $this->phyId ?>" name="pid">
           <td><input type="submit" value="Accept"></td>
         </form>
            </tr>
            <?php
}
?>
</table>

<?php
echo "<h3>Accepted</h3>";
 echo "<table>";
 echo"<tr>";
         echo "<td>Description</td>";
         echo "<td>Date</td>";
            echo"</tr>";
foreach ($this->accVisits as $accepted) {
    ?>
           <tr>
          <td><?= $accepted["description"] ?></td>
          <td><?= $accepted["created_date"] ?></td>
          <td><a href='cancel/vid/<?= $accepted['id'] ?>/pid/<?= $this->phyId ?>'>Cancel</a></td>
            <td><a href='live/patientId/<?= $accepted['patient_id'] ?>/vid/<?= $accepted['id'] ?>/phyid/<?= $accepted['physican_id'] ?>'>Go Live</a></td>

            </tr>
            <?php
}
?>
</table>

<?php
echo "<h3>Previous</h3>";
 echo "<table>";
 echo"<tr>";
         echo "<td>Description</td>";
         echo "<td>Date</td>";
            echo"</tr>";
foreach ($this->preVisits as $pre) {
    ?>
           <tr>
          <td><?= $pre["description"] ?></td>
          <td><?= $pre["created_date"] ?></td>

            </tr>
            <?php
}
?>
</table> 
