
<br /><br />
<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/scripts.js"></script>
<link href="<?= $this->baseUrl() ?>/css/style.css" rel="stylesheet">
<link href="<?= $this->baseUrl() ?>/css/tableStyle.css" rel="stylesheet">
<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/jquery-ui.min.css" type="text/css" />
<link href="<?= $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/fts-webrtc-styles.css">


<style>
    .searchtext{
        float: left;
    }
    .searchbtn{
      top: -7px;
      position: relative;
        left: 48px;
    }
    .box
    {
        width:178px;
        position: relative;
        top: -22px;
        left: 6px;
    }
    .container{
        width: 600px;
        float: right;
    }
    .panel-body{
        height: 305px;
        overflow: auto;
        padding: 0px;
        
    }
    .presc
    {
        float:left;
        margin: 5px;
    }
    .presccontainer
    {
        top: 300px;
position: relative;
}

.notes{
    left:590px;
    position: relative;
        top:-45px;
}
#notes{
    width: 572px;
    height: 300px;
}
    
#videoconf{
    position: absolute;
    left:5px;
    top:5px;
    height: 330px;
    background-color: yellowgreen;
    width: 650px;
}
table{
    width:100%;
    margin: 0px;
}
</style>

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="panel-group" id="panel-522543">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-522543" href="#panel-element-900591">Patient Information</a>
                    </div>
                    <div id="panel-element-900591" class="panel-collapse in">
                        <div class="panel-body">
                            <table style="height:100%">
                                <tr>
                                    
                                     <th>Name</th>
                                     <td><?= $this->fullData["name"]?></td>
                                </tr>
                        <tr>
                                    
                                     <th>Gender</th>
                                     <?php
                                      if ($this->fullData["sex"] == 'F') {
                                    echo "<td>Female</td>";
                                } elseif ($this->fullData["sex"] == 'M') {
                                    echo "<td>Male</td>";
                                }
                                ?>
                                </tr>
                               <tr>
                                    
                                     <th>Martial Status</th>
                                     <td><?= $this->fullData["martial_status"]?></td>
                                </tr>
                             <tr>
                                    
                                     <th>Birth Date</th>
                                     <td><?= $this->fullData["DOB"]?></td>
                                </tr>
                                 <tr>
                                    
                                     <th>Join Date</th>
                                     <td><?= $this->fullData["join_date"]?></td>
                                </tr>
                                 <tr>
                                    
                                     <th>Job</th>
                                     <td><?= $this->fullData["job"]?></td>
                                </tr>
                            
                               </table>
                           
                          
                      
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="panel-title" data-toggle="collapse" data-parent="#panel-522543" href="#panel-element-812733">Vitals</a>
                    </div>
                    <div id="panel-element-812733" class="panel-collapse collapse">
                        <div class="panel-body" >
                            <?php
                            if($this->VitalData){?>
                            
                           
                            
                              <table >
                                <tr>
                                    
                                     <th>Vital</th>
                                     <th>Data</th>
                                    
                                </tr>
                          <?php
                           foreach ($this->VitalData as $value) {
                               ?>
                               <tr>
                             
                               <td><?= $value["vital_name"]?></td>
                               <td><?= $value["data"]?></td>
                               
                               </tr>
                               
                               <?php
                           }
                          
                          
                              ?>
                               </table>
                            <?php } ?>
                                     </div>
                    </div>
                </div>
                <!--begain-->
                 <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="panel-title" data-toggle="collapse" data-parent="#panel-522543" href="#panel-element-1">Radiation</a>
                    </div>
                    <div id="panel-element-1" class="panel-collapse collapse">
                        <div class="panel-body">
                            photo
                        </div>
                    </div>
                </div>
                <!--end-->
                 <!--begain-->
                 <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="panel-title" data-toggle="collapse" data-parent="#panel-522543" href="#panel-element-2">Tests</a>
                    </div>
                    <div id="panel-element-2" class="panel-collapse collapse">
                        <div class="panel-body">
                              <table >
                                <tr>
                                    
                                     <th>Test</th>
                                     <th>Data</th>
                                    
                                </tr>
                          <?php
                           foreach ($this->TestData as $value) {
                               ?>
                               <tr>
                             
                               <td><?= $value["test_name"]?></td>
                               <td><?= $value["data"]?></td>
                               
                               </tr>
                               
                               <?php
                           }
                          
                          
                              ?>
                               </table>
                        </div>
                    </div>
                </div>
                <!--end-->
                 <!--begain-->
                 <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="panel-title" data-toggle="collapse" data-parent="#panel-522543" href="#panel-element-3">Medications</a>
                    </div>
                    <div id="panel-element-3" class="panel-collapse collapse">
                        <div class="panel-body">
                           <table >
                                <tr>
                                    <th>Physician</th>
                                     <th>Medication</th>
                                     <th>Date</th>
                                </tr>
                          <?php
                           foreach ($this->medicationData as $value) {
                               ?>
                               <tr>
                               <td><?= $value["physician"]?></td>
                               <td><?= $value["medication"]?></td>
                               <td><?= $value["date"]?></td>
                               </tr>
                               
                               <?php
                           }
                          
                          
                              ?>
                               </table>
             
                        </div>
                    </div>
                </div>
                <!--end-->
                 <!--begain-->
                 <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="panel-title" data-toggle="collapse" data-parent="#panel-522543" href="#panel-element-4">Disease</a>
                    </div>
                    <div id="panel-element-4" class="panel-collapse collapse">
                        <div class="panel-body">
                           
                             <table >
                                <tr>
                                    
                                     <th>Disease</th>
                                     <th>Date</th>
                                </tr>
                          <?php
                           foreach ($this->diseaseData as $value) {
                               ?>
                               <tr>
                               <td><?= $value["disease"]?></td>
                               <td><?= $value["date"]?></td>
                               
                               </tr>
                               
                               <?php
                           }
                          
                          
                              ?>
                               </table>
                        </div>
                    </div>
                </div>
                <!--end-->
                  <!--begain-->
                 <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="panel-title" data-toggle="collapse" data-parent="#panel-522543" href="#panel-element-5">Surgery</a>
                    </div>
                    <div id="panel-element-5" class="panel-collapse collapse">
                        <div class="panel-body">
                              <table >
                                <tr>
                                    
                                     <th>Surgery</th>
                                     <th>Date</th>
                                </tr>
                          <?php
                           foreach ($this->surgeryData as $value) {
                               ?>
                               <tr>
                             
                               <td><?= $value["surgery"]?></td>
                               <td><?= $value["date"]?></td>
                               </tr>
                               
                               <?php
                           }
                          
                          
                              ?>
                               </table>
                        </div>
                    </div>
                </div>
                <!--end-->
            </div>
        </div>
    </div>
</div>
<div id="videoconf">
    Here Video Conference
    <div id="mainContainer" class="main-container">

        <?php

        echo 'Video Conference';

        ?>
            <div style="position: absolute;left: 0px; top: 0px ; z-index: -1">
            <div class="change">
                <!-- local video -->
                <video id="localVideo" class="local-video"></video>

                <!-- remote video -->
                <div style="">

                    <video id="remoteVideo" class="remote-video" autoplay  ></video>
                </div>

                <!-- video status & room entry bar -->
                <div id="videoStatus" class="video-status">
                </div>


            </div>
            </div>
        </div>
</div>

<div class="presccontainer">
<form action="" method="post">
    
<div class="presc">
    <?= $this->prescriptionForm->dissearch;?>
    <?= $this->prescriptionForm->disAdd;?>
    <?= $this->prescriptionForm->disease_id;?>
    <?= $this->prescriptionForm->disbox;?>
</div>
<div class="presc">
    <?= $this->prescriptionForm->medsearch;?>
    <?= $this->prescriptionForm->medAdd;?>
    <?= $this->prescriptionForm->medication_id;?>
    <?= $this->prescriptionForm->medbox;?>
</div >

<div class="presc">
    <?= $this->prescriptionForm->radsearch;?>
    <?= $this->prescriptionForm->radAdd;?>
    <?= $this->prescriptionForm->radiation_id;?>
    <?= $this->prescriptionForm->radbox;?>
</div>

<div class="presc">
    <?= $this->prescriptionForm->vitsearch;?>
    <?= $this->prescriptionForm->vitAdd;?>
    <?= $this->prescriptionForm->vital_id;?>
    <?= $this->prescriptionForm->vitbox;?>
</div>

<div class="presc">
    <?= $this->prescriptionForm->testsearch;?>
    <?= $this->prescriptionForm->testAdd;?>
    <?= $this->prescriptionForm->test_id;?>
    <?= $this->prescriptionForm->testbox;?>
</div>

<div class="presc">
    <?= $this->prescriptionForm->sursearch;?>
    <?= $this->prescriptionForm->surAdd;?>
    <?= $this->prescriptionForm->surgery_id;?>
    <?= $this->prescriptionForm->surbox;?>
</div>


<div style="float: right" class="notes">
 <?= $this->prescriptionForm->notes;?>
    </div>
<div class="presc">
 <?= $this->prescriptionForm->submit;?>
</div>
</form>
</div>

<script>

    function autocomp(type)
    {

        $(function() {
            //autocomplete
            switch (type) {
                case 'medication':

                    var medication = document.getElementById("medsearch").value;

                    $("#medsearch").autocomplete({
                        source: "<?= $this->baseUrl() ?>/Autocomplete/get-Medication/medication/" + medication + "",
                        minLength: 1

                    });
                    $('#medication_id').find('option').remove();


                    $.getJSON("<?= $this->baseUrl() ?>/Autocomplete/get-Medication/medication/" + medication + "", function(data) {
                        $.each(data, function(index, item) {
                            $('#medication_id').append(
                                    $('<option></option>').val(index).html(item)
                                    );
                        });

                    });


                    break;
                case 'disease':
                    var disease = document.getElementById("dissearch").value;

                    $("#dissearch").autocomplete({
                        source: "<?= $this->baseUrl() ?>/Autocomplete/get-Disease/disease/" + disease + "",
                        minLength: 1

                    });
                    $('#disease_id').find('option').remove();


                    $.getJSON("<?= $this->baseUrl() ?>/Autocomplete/get-Disease/disease/" + disease + "", function(data) {
                        $.each(data, function(index, item) {
                            $('#disease_id').append(
                                    $('<option></option>').val(index).html(item)
                                    );
                        });

                    });

                    break;
                case 'radiation':
                    var radiation = document.getElementById("radsearch").value;

                    $("#radsearch").autocomplete({
                        source: "<?= $this->baseUrl() ?>/Autocomplete/get-Radiation/radiation/" + radiation + "",
                        minLength: 1

                    });
                    $('#radiation_id').find('option').remove();


                    $.getJSON("<?= $this->baseUrl() ?>/Autocomplete/get-Radiation/radiation/" + radiation + "", function(data) {
                        $.each(data, function(index, item) {
                            $('#radiation_id').append(
                                    $('<option></option>').val(index).html(item)
                                    );
                        });

                    });

                    break
                case 'surgery':
                    var surgery = document.getElementById("sursearch").value;

                    $("#sursearch").autocomplete({
                        source: "<?= $this->baseUrl() ?>/Autocomplete/get-Surgery/surgery/" + surgery + "",
                        minLength: 1

                    });
                    $('#surgery_id').find('option').remove();


                    $.getJSON("<?= $this->baseUrl() ?>/Autocomplete/get-Surgery/surgery/" + surgery + "", function(data) {
                        $.each(data, function(index, item) {
                            $('#surgery_id').append(
                                    $('<option></option>').val(index).html(item)
                                    );
                        });

                    });

                    break;
                case 'test':
                    var test = document.getElementById("testsearch").value;

                    $("#testsearch").autocomplete({
                        source: "<?= $this->baseUrl() ?>/Autocomplete/get-Test/test/" + test + "",
                        minLength: 1

                    });
                    $('#test_id').find('option').remove();


                    $.getJSON("<?= $this->baseUrl() ?>/Autocomplete/get-Test/test/" + test + "", function(data) {
                        $.each(data, function(index, item) {
                            $('#test_id').append(
                                    $('<option></option>').val(index).html(item)
                                    );
                        });

                    });

                    break;
                case  'vital':
                    var vital = document.getElementById("vitsearch").value;

                    $("#vitsearch").autocomplete({
                        source: "<?= $this->baseUrl() ?>/Autocomplete/get-Vital/vital/" + vital + "",
                        minLength: 1

                    });
                    $('#vital_id').find('option').remove();


                    $.getJSON("<?= $this->baseUrl() ?>/Autocomplete/get-Vital/vital/" + vital + "", function(data) {
                        $.each(data, function(index, item) {
                            $('#vital_id').append(
                                    $('<option></option>').val(index).html(item)
                                    );
                        });

                    });
                    break;

            }




        });
    }
</script>

<script>
    function HandleKey(type) {
        switch (type) {
            case 'medication':
                k = document.getElementById('medsearch');

                break;
            case 'disease':
                k = document.getElementById('dissearch');
                break;
            case 'radiation':
                k = document.getElementById('radsearch');
                break
            case 'surgery':
                k = document.getElementById('sursearch');
                break;
            case 'vital':
                k = document.getElementById('vitsearch');
                break;
            case 'test':
                k = document.getElementById('testsearch');
                break;
        }
        var keys = k.value;

        if (keys.length > 0) {
            FindKey(keys, type);
        }

    }

    function FindKey(keys, type) {
        switch (type) {
            case 'medication':
                opts = document.getElementById('medication_id');

                break;
            case 'disease':
                opts = document.getElementById('disease_id');
                break;
            case 'radiation':
                opts = document.getElementById('radiation_id');
                break
            case 'surgery':
                opts = document.getElementById('surgery_id');
                break;
            case 'vital':
                opts = document.getElementById('vital_id');
                break;
            case 'test':
                opts = document.getElementById('test_id');
                break;
        }

        for (i = 0; i < opts.length; i++) {
            var array = [opts.item(i).text];
            if (array[0] == keys)
            {
                opts.selectedIndex = opts.item(i).index;
            }
            if (opts.item(i).text.substr(0, keys.length) == keys) {
// Select the option opts.item(i)
                document.selectedIndex = i;
                return false;
            }
        }
    }

    function addtobox(type)
    {
        switch (type)
        {
            case 'medication':
                opts = document.getElementById('medication_id');
                box = document.getElementById("medbox");
                key = document.getElementById('medsearch');
                break;
            case 'disease':
                opts = document.getElementById('disease_id');
                box = document.getElementById("disbox");
                key = document.getElementById('dissearch');
                break;
            case 'radiation':
                opts = document.getElementById('radiation_id');
                box = document.getElementById("radbox");
                key = document.getElementById('radsearch');
                break
            case 'surgery':
                opts = document.getElementById('surgery_id');
                box = document.getElementById("surbox");
                key = document.getElementById('sursearch');
                break;
            case 'vital':
                opts = document.getElementById('vital_id');
                box = document.getElementById("vitbox");
                key = document.getElementById('vitsearch');
                break;
            case 'test':
                opts = document.getElementById('test_id');
                box = document.getElementById("testbox");
                key = document.getElementById('testsearch');
                break;
        }
        if (!isfound(box, opts.item(opts.selectedIndex).value)) {
            if (key.value == opts.item(opts.selectedIndex).text) {
                box.options[box.options.length] = new Option(opts.item(opts.selectedIndex).text, opts.item(opts.selectedIndex).value, true, true);
            }
        }

    }
    function isfound(list, v)
    {

        flag = false;
        for (i = 0; i < list.length; i++) {
            var array = [list.item(i).value];
            if (array[0] == v)
            {
                flag = true;
            }

        }
        return flag;
    }

</script>

<script src="<?= $this->baseUrl() ?>/js/jquery.fresh-tilled-soil-webrtc.js"></script>

<!-- Plugin Initialization -->
<script type="text/javascript">
    
	$(function() {
		$('#mainContainer').createVideoChat();
	});
</script>