<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui.min.js"></script>
<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/jquery-ui.min.css" type="text/css" /> 
<table>
    <tr>
        <td>
            <h2>Vitals</h2>
            <form action="" method="post">
                Vital Type : <input type="text" id="vital" name="vital" placeholder="Type Vital Name" />  
            </form>
            <input type="submit" value="Add" onclick="addRequestedVital()"/>
        </td>
        <td>
            <h2>Radiations</h2>
            <form action="" method="post">
                Radiation Type : <input type="text" id="radiation" name="radiation" placeholder="Type Radiation Name"/>
            </form>
            <input type="submit" value="Add" onclick="addRequestedRadiation()"/>
        </td>
        <td>
            <h2>Tests</h2>
            <form action="" method="post">
                Test Type : <input type="text" id="test" name="test" placeholder="Type Test Name"/>
            </form>
            <input type="submit" value="Add" onclick="addRequestedTest()"/>
        </td>
    </tr>
    <tr>
        <td>
            <div id="vitalDiv" style="background-color: rgb(250, 250, 250);height: 153px;border-radius: 4px;border-style: solid;border-width: 1px;border-color: #DBDBDB;"></div>
        </td>
        <td>
            <div id="radiationDiv" style="background-color: rgb(250, 250, 250);height: 153px;border-radius: 4px;border-style: solid;border-width: 1px;border-color: #DBDBDB;"></div>
        </td>
        <td>
            <div id="testDiv" style="background-color: rgb(250, 250, 250);height: 153px;border-radius: 4px;border-style: solid;border-width: 1px;border-color: #DBDBDB;"></div>
        </td>
    </tr>
</table>
<h3><a href="view/id/<?= $this->visitId ?>">>>Finish</a></h3>

<script type="text/javascript">
    visitId = <?= $this->visitId ?>;
$(function() {
	//autocomplete
	$("#vital").autocomplete({
		source: "<?= $this->baseUrl() ?>/Autocomplete/get-Vital",
		minLength: 1
	});	
        
        $("#radiation").autocomplete({
		source: "<?= $this->baseUrl() ?>/Autocomplete/get-Radiation",
		minLength: 1
	});
        
        $("#test").autocomplete({
		source: "<?= $this->baseUrl() ?>/Autocomplete/get-Test",
		minLength: 1
	});
        
});

function addRequestedVital() {
    vital = document.getElementById('vital').value;
    var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {
            if(xhr.readyState === 4) {
                if(this.responseText === 'done') {
                    element = document.createElement("div");
                    element.innerHTML = vital;
                    document.getElementById('vital').value = "";
                    $vitalDiv = document.getElementById('vitalDiv');
                    $vitalDiv.appendChild(element);
                }
                else {$vitalDiv.textContent = vital;
                    alert(this.responseText);
                }
            }
        };

        xhr.open("get","<?=$this->baseUrl()?>/Ajax/add-vital?vital="+vital+"&visitId="+visitId);
        xhr.send();
}

function addRequestedRadiation() {
    radiation = document.getElementById('radiation').value;
    var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {
            if(xhr.readyState === 4) {
                if(this.responseText === 'done') {
                    element = document.createElement("div");
                    element.innerHTML = radiation;
                    document.getElementById('radiation').value = "";
                    $radDiv = document.getElementById('radiationDiv');
                    $radDiv.appendChild(element);
                }
                else {
                    alert(this.responseText);
                }
            }
        };

        xhr.open("get","<?=$this->baseUrl()?>/Ajax/add-radiation?radiation="+radiation+"&visitId="+visitId);
        xhr.send();
}

function addRequestedTest() {
    test = document.getElementById('test').value;
    var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {
            if(xhr.readyState === 4) {
                if(this.responseText === 'done') {
                    element = document.createElement("div");
                    element.innerHTML = test;                    
                    document.getElementById('test').value = "";
                    $testDiv = document.getElementById('testDiv');
                    $testDiv.appendChild(element);
                }
                else {
                    alert(this.responseText);
                }
            }
        };

        xhr.open("get","<?=$this->baseUrl()?>/Ajax/add-test?test="+test+"&visitId="+visitId);
        xhr.send();
}
</script>
