<script>

$(document).ready(function() {

var date = new Date();
var d = date.getDate();
var m = date.getMonth();
var y = date.getFullYear();

$('#calendar').fullCalendar({
    header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
    },
    editable: false,
    events: <?= $this->allVisitsJson ?>,
    eventClick: function(event) {
        window.open(event.url, 'gcalevent', 'width=600,height=600');
        return false;
    }
    
});

});

</script>
<style>
	#calendar {
		width: 750px;
		margin: 0 auto;
                float: left;
		}
</style>
<div class="row clearfix">
    <div class="col-md-2 column">
            <div class="panel panel-info">
                <div class="panel-heading" style="background-color: #22475E">
                  <h3 class="panel-title"><i class="fa fa-spinner fa-fw"></i>Pending Visits</h3>
                </div>
                
             
            <?php
                $checkFound = TRUE;
                if($this->allVisitsJson != "null")
                {
                    foreach (json_decode($this->allVisitsJson) as $visit) {
                        if(!$visit->start) {
                            $checkFound = FALSE;
                            ?>
                                <div class="panel-body">
                                    <a href="/Nubia/public/patient"><?= $visit->title ?></a>
                                </div>
                            <?php
                        }
                    }
                }
                
                if($checkFound) {
                    echo "No Pending Events !!";
                }
            ?>
        </div>
    </div>
    <div class="col-md-10 column" style="float: left">
        <div id='calendar'></div>
    </div>
</div>