<br /><br />
<div id="view-content">
    <h1>Visits :</h1>
    <h2>Visits Statistics : </h2>
    <ul>
        <li>
            <b>Number of Visits : </b>
        </li>
        <li>
            <b>Last Added Visit : --------</b>
        </li>
    </ul>
  
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/Visit/add">Add Visit</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Visit/search/delete/1">Delete Visit</a></li><!--lsaaaaaaaaaaaaa-->
        <li><a href="<?= $this->baseUrl() ?>/Visit/search/edit/1">Edit Visit</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Visit/search">Search Visits</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Visit/list">List Visits</a></li>
        
    </ul>
</div>