<br /><br />

<table class='table table-bordered table-hover table-condensed' id='prescriptionTable' border='1' cellpadding='3'>
<thead>
  <tr>
    <th>Dr.</th>
    <td><?=$this->visitData["phyname"]?></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><?=$this->visitData["patname"]?></td>
  </tr>
  <tr>
    <th>Date</th>
    <td><?=substr($this->visitData["date"],0,10)?></td>
  </tr>
<?php
if($this->medicationData)
{
    $medication = $this->medicationData;
    echo "
    <tr>
    <th rowspan='".count($medication)."'>Medications</th>";
    for($i = 0 ; $i < count($medication) ; $i++)
    {
        if($i == 0)
            echo "<td>".$medication[$i]["medication"]." </td></tr>";
        else
            echo "<tr><td>".$medication[$i]["medication"]."</td></tr>";
    }
}
if($this->surgeryData)
{
    $surgery = $this->surgeryData;
    echo "<tr>
    <th rowspan='".count($surgery)."'>Surgery</th>";
    for($i = 0 ; $i < count($surgery) ; $i++)
    {
        if($i == 0)
            echo "<td>".$surgery[$i]["surgery"]." ( ".$surgery[$i]["date"]." ) "." </td></tr>";
        else
            echo "<tr><td>".$surgery[$i]["surgery"]." ( ".$surgery[$i]["date"]." ) "."</td></tr>";
    }
    
}
?>
</thead>
</table>
<!--<td rowspan="2">1</td>-->
<button onclick="printPrescription()">print prescription</button>
<script>
    function printPrescription()
    {
        var prescription = document.getElementById('prescriptionTable');
        newWin = window.open("");
        newWin.document.write(prescription.outerHTML);
        newWin.print();
        newWin.close();
    }
</script>