<br /><br />

<table class='table table-bordered table-hover table-condensed' id='prescriptionTable' border='1' cellpadding='3'>
<thead>
  <tr>
    <th>Dr.</th>
    <td><?=$this->visitData["phyname"]?></td>
  </tr>
  <tr>
    <th>Patient</th>
    <td><?=$this->visitData["patname"]?></td>
  </tr>
  <tr>
    <th>Date</th>
    <td><?=substr($this->visitData["date"],0,10)?></td>
  </tr>
<?php
if($this->medicationData)
{
    $medication = $this->medicationData;
    echo "
    <tr>
    <th rowspan='".count($medication)."'>Medications</th>";
    for($i = 0 ; $i < count($medication) ; $i++)
    {
        if($i == 0)
            echo "<td>".$medication[$i]["medication"]." </td></tr>";
        else
            echo "<tr><td>".$medication[$i]["medication"]."</td></tr>";
    }
}
if($this->surgeryData)
{
    $surgery = $this->surgeryData;
    echo "<tr>
    <th rowspan='".count($surgery)."'>Surgery</th>";
    for($i = 0 ; $i < count($surgery) ; $i++)
    {
        if($i == 0)
            echo "<td>".$surgery[$i]["surgery"]." ( ".$surgery[$i]["date"]." ) "." </td></tr>";
        else
            echo "<tr><td>".$surgery[$i]["surgery"]." ( ".$surgery[$i]["date"]." ) "."</td></tr>";
    }
    
}
if($this->diseaseData)
{
    $disease = $this->diseaseData;
    echo "<tr>
    <th rowspan='".count($disease)."'>Disease</th>";
    for($i = 0 ; $i < count($disease) ; $i++)
    {
        if($i == 0)
            echo "<td>".$disease[$i]["disease"]."</td></tr>";
        else
            echo "<tr><td>".$disease[$i]["disease"]."</td></tr>";
    }
    
}
if($this->radiationData)
{
    $radiation = $this->radiationData;
    echo "
    <tr>
    <th rowspan='".count($radiation)."'>Radiations</th>";
    for($i = 0 ; $i < count($radiation) ; $i++)
    {
        if($i == 0)
            echo "<td>".$radiation[$i]["radiationName"]." </td></tr>";
        else
            echo "<tr><td>".$radiation[$i]["radiationName"]."</td></tr>";
    }
}
if($this->vitalData)
{
    $vital = $this->vitalData;
    echo "
    <tr>
    <th rowspan='".count($vital)."'>Vitals</th>";
    for($i = 0 ; $i < count($vital) ; $i++)
    {
        if($i == 0)
            echo "<td>".$vital[$i]["vitalName"]." </td></tr>";
        else
            echo "<tr><td>".$vital[$i]["vitalName"]."</td></tr>";
    }
}
if($this->testData)
{
    $test = $this->testData;
    echo "
    <tr>
    <th rowspan='".count($test)."'>Tets</th>";
    for($i = 0 ; $i < count($test) ; $i++)
    {
        if($i == 0)
            echo "<td>".$test[$i]["testName"]." </td></tr>";
        else
            echo "<tr><td>".$test[$i]["testName"]."</td></tr>";
    }
}
?>
</thead>
</table>
<!--<td rowspan="2">1</td>-->
<button onclick="printPrescription()">print prescription</button>
<script>
    function printPrescription()
    {
        var prescription = document.getElementById('prescriptionTable');
        newWin = window.open("");
        newWin.document.write(prescription.outerHTML);
        newWin.print();
        newWin.close();
    }
</script>