<br /><br />
<div id="view-content">
	<p>View script for controller <b>Visit</b> and script/action name <b>prescription</b></p>
</div>
<?php
var_dump($this->medicationData);
var_dump($this->surgeryData);
?>

<?php
if($this->medicationData)
{
    echo "<table class='table table-bordered table-hover table-condensed' contenteditable='true'>
      <thead>
        <tr>
          <th>Dr.</th>
          <td>".$this->medicationData[0]["physician"]."</td>
        </tr>
        <tr>
          <th>Name</th>
          <td>".$this->medicationData[0][""]."</td>
        </tr>
        <tr>
          <th>Date</th>
          <td>".substr($this->medicationData[0]["date"],0,10)."</td>
        </tr>
        <tr>
          <th>Medications</th>
          <th>";
            foreach ($this->medicationData as $medication)
            {
                echo $medication["medication"]." - ";
            }   
            echo "test1";
         echo "</th>";
        echo "</tr>
        <tr>
          <th>Surgery</th>
          <th>";
            foreach ($this->surgeryData as $surgery)
            {
                echo $surgery["surgery"]." - ";
            }   
            echo "test1";
         echo "</th>
        </tr>
      </thead>
      <tbody>";
    echo "</tbody>
    </table>";
}
?>
<!--<td rowspan="2">1</td>-->