<div class="row clearfix">
    <div class="col-md-6 column">
        <span class="label label-primary" style="font-size: 25px">Visits Search</span>
        <br><br>
        <form class="form-horizontal" method="POST">
            <fieldset>
                <legend>Search</legend>
                <div class="form-group">
                  <label for="key" class="col-lg-2 control-label">Visit</label>
                  <div class="col-lg-10">
                      <input name="date" type="date" placeholder="YYYY-MM-DD" class="form-control"/>
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-lg-10 col-lg-offset-2">
                      <input type="submit" value="Search" class="btn btn-primary"/>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
    <div class="col-md-3 column"></div>
</div>
<div class="row clearfix">
    <div class="col-md-12 column">
  <?php
        if($this->visits){
            echo "<table class='table table-striped table-hover'>";
            echo "<tr><th>Date</th>";
            echo "<th>Description</th>";
            echo "<th>Physician Name</th>";
            echo "<th>Patient Name</th>";
            echo "<th>Type</th>";
            echo "<th>Notes</th>";
            echo "<th>GP Name</th></tr>";
            foreach ($this->visits as $visit) {
                echo "<tr>";
                echo "<td>".$visit["date"]."</td>";
                echo "<td>".$visit["description"]."</td>";
                echo "<td>".$visit["phyname"]."</td>";
                echo "<td>".$visit["patname"]."</td>";
                echo "<td>".$visit["type"]."</td>";
                echo "<td>".$visit["notes"]."</td>";
                echo "<td>".$visit["gpname"]."</td>";
                echo "<td>";
                echo "<a href='". $this->baseUrl()."/visit/edit?id=".$visit["id"]."'> Edit </a>";
                echo "<a href='". $this->baseUrl()."/visit/delete?id=".$visit["id"]."'> - Delete </a>";
                echo "<a href='". $this->baseUrl()."/test-result/view?dep=all&reqid=".$visit["id"]."'> - Depandency </a>";
    //            if($currentDate == substr($visit["date"],0,10) )
                    echo "<a href='". $this->baseUrl()."/visit/live?patid=".$visit["patient_id"]."&visid=".$visit["id"]."' target='_blanck'> - Start Visit </a>";
                echo "</td>";
                echo "</tr>";
            }
            echo "</table>";
    }   
        ?>        
    </div>
        <?php
        if($this->dataNotFound){
            echo "No visits were found at that date";
        }
        ?>
        <br><a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>


