<br /><br />
<div id="view-content">
    <div>
        <form action="" method="post">
            <input name="date" type="date" placeholder="YYYY-MM-DD" >
            <input type="submit">

        </form>
    </div>
    <div>
        <?php
        if($this->visits){
            echo "<table>";
            echo "<tr><th>Date</th>";
            echo "<th>Description</th>";
            echo "<th>Physician Name</th>";
            echo "<th>Patient Name</th>";
            echo "<th>Type</th>";
            echo "<th>Notes</th>";
            echo "<th>GP Name</th></tr>";
            foreach ($this->visits as $visit) {
                echo "<tr>";
                echo "<td>".$visit["date"]."</td>";
                echo "<td>".$visit["description"]."</td>";
                echo "<td>".$visit["phyname"]."</td>";
                echo "<td>".$visit["patname"]."</td>";
                echo "<td>".$visit["type"]."</td>";
                echo "<td>".$visit["notes"]."</td>";
                echo "<td>".$visit["gpname"]."</td>";
                echo "<td>";
                echo "<a href='". $this->baseUrl()."/visit/edit?id=".$visit["id"]."'> Edit </a>";
                echo "<a href='". $this->baseUrl()."/visit/delete?id=".$visit["id"]."'> - Delete </a>";
                echo "<a href='". $this->baseUrl()."/test-result/view?dep=all&reqid=".$visit["id"]."'> - Depandency </a>";
    //            if($currentDate == substr($visit["date"],0,10) )
                    echo "<a href='". $this->baseUrl()."/visit/live?patid=".$visit["patient_id"]."&visid=".$visit["id"]."' target='_blanck'> - Start Visit </a>";
                echo "</td>";
                echo "</tr>";
            }
            echo "</table>";
    }   
        ?>        
    </div>
    <div>
        <?php
        if($this->dataNotFound){
            echo "No visits were found at that date";
        }
        ?>
    </div>
</div>
