<br /><br />
<div id="view-content">
    <tr>
        <td>Date : </td>
        <td><?=$this->visit["date"]?></td>
        
        </tr>
        </br>
         <tr>
             <td>Description : </td>
        <td><?=$this->visit["description"]?></td>
        
        </tr>
        </br>
         <tr>
             <td>Physician Name : </td>
        <td><?=$this->visit["phyname"]?></td>
        
        </tr>
        </br>
         <tr>
             <td>Patient Name : </td>
        <td><?=$this->visit["patname"]?></td>
        
        </tr>
        </br>
         <tr>
             <td>Type : </td>
        <td><?=$this->visit["type"]?></td>
        
        </tr>
        </br>
         <tr>
             <td>Notes : </td>
        <td><?=$this->visit["notes"]?></td>
        
        </tr>
        </br>
        <tr>
            <td>GP Name : </td>
        <td><?=$this->visit["gpname"]?></td>
        
        </tr>
        
</div>