<div class="row clearfix">
    <div class="col-md-2 column"></div>
<?php
$currentDate = date('Y-m-d');
if($this->visit)
{
    ?>
        <div class='col-md-8 column'>
        <span class='label label-primary' style='font-size: 25px'>Visit Details</span>
        <br><br>
        <?php
    if($this->visit["created_date"])
    {
        if($currentDate > substr($this->visit["created_date"],0,10))
            echo "<span class='label label-default' style='font-size: 15px'><i class='fa fa-backward fa-fw'></i> Previous</span>";
        else
            echo "<span class='label label-success' style='font-size: 15px' ><i class='fa fa-play-circle fa-fw'></i> Accepted</span>";
    }
    else {
        ?>
    <span class='label label-danger' style='font-size: 15px'><i class='fa fa-pause fa-fw'></i> Pending</span>
    <?php } ?>
    <br>
    
  <table class='table table-striped table-hover'>
    <tr>
        <td>Date: </td>
        <td><?=$this->visit["created_date"]?></td>
        
        </tr>
        
         <tr>
             <td>Description: </td>
        <td><?=$this->visit["description"]?></td>
        
        </tr>
        
         <tr>
             <td>Physician: </td>
        <td><?=$this->visit["phyname"]?></td>
        
        </tr>
        
         <tr>
             <td>Patient: </td>
        <td><?=$this->visit["patname"]?></td>
        
        </tr>
        
         <tr>
             <td>Type: </td>
        <td><?=$this->visit["type"]?></td>
        
        </tr>
        
         <tr>
             <td>Notes: </td>
        <td><?=$this->visit["notes"]?></td>
        
        </tr>
        
        <tr>
            <td>GP: </td>
        <td><?=$this->visit["gpname"]?></td>
        
        </tr>
        </table>

    <div>
        <?php
    if($this->userType != "physician")
    {
        if($currentDate <= substr($visit["created_date"],0,10))
            echo "<a href='". $this->baseUrl()."/visit/edit?id=".$this->visit["id"]."' class='btn btn-default'> Edit </a>";
        echo "<a href='". $this->baseUrl()."/visit/delete?id=".$this->visit["id"]."'  class='btn btn-default'> Delete </a>";
    }
    echo "<a href='". $this->baseUrl()."/visit/dependancy?dep=all&reqid=".$this->visit["id"]."' class='btn btn-danger'> Depandency </a>";
    if($currentDate == substr($this->visit["created_date"],0,10) )
        echo "<a href='". $this->baseUrl()."/visit/live?patid=".$this->visit["patient_id"]."&visid=".$this->visit["id"]."' target='_blanck' class='btn btn-success'> Start Visit </a>";
    if($currentDate >= substr($this->visit["created_date"],0,10) || $this->visit["date"] == $this->visit["created_date"])
        echo "<a href='". $this->baseUrl()."/visit/prescription?visitid=".$this->visit["id"]."' target='_blanck' class='btn btn-info'> Prescription </a>";
    echo "</div>";
}
    else if($this->visits)
    {
        $visit = $this->visits;
        echo "
        <div class='col-md-12 column'>
        <span class='label label-primary' style='font-size: 25px'>Visits List</span>
        <br><br>
        ";
        echo "<table class='table table-striped table-hover'>";
        echo "<thead><tr><th>Date</th>";
        echo "<th>Description</th>";
        echo "<th>Physician</th>";
        echo "<th>Patient</th>";
        echo "<th>Type</th>";
        echo "<th>Notes</th>";
        echo "<th>GP</th>";
        echo "<th>Action</th></tr></thead>";
        foreach ($this->paginator as $visit) {
            echo "<tr>";
            echo "<td>".$visit["created_date"]."</td>";
            echo "<td>".$visit["description"]."</td>";
            echo "<td>".$visit["phyname"]."</td>";
            echo "<td>".$visit["patname"]."</td>";
            echo "<td>".$visit["type"]."</td>";
            echo "<td>".$visit["notes"]."</td>";
            echo "<td>".$visit["gpname"]."</td>";
            echo "<td>";
            if($this->userType != "physician")
            {
                if($currentDate <= substr($visit["created_date"],0,10))
                    echo "<a href='". $this->baseUrl()."/visit/edit?id=".$visit["id"]."' class='btn btn-default'> Edit </a>";
                echo "<a href='". $this->baseUrl()."/visit/delete?id=".$visit["id"]."' class='btn btn-default'> Delete </a>";
            }
            echo "<a href='". $this->baseUrl()."/visit/dependancy?dep=all&reqid=".$visit["id"]."' class='btn btn-danger'> Dependency</a>";
            if($currentDate == substr($visit["created_date"],0,10) )
                echo "<a href='". $this->baseUrl()."/visit/live?patid=".$visit["patient_id"]."&visid=".$visit["id"]."' target='_blanck' class='btn btn-success'> Start Visit </a>";
            if($currentDate >= substr($visit["created_date"],0,10) || $visit["date"] == $visit["created_date"])
                echo "<a href='". $this->baseUrl()."/visit/prescription?visitid=".$visit["id"]."' target='_blanck' class='btn btn-info'> Prescription </a>";
            echo "</td>";
            echo "</tr>";
        }
        echo "</table>";
        echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml',array('patID' => $this->patID));
    }
    else
        echo "<h2>NO VISITS</h2>"."<a href='".$this->baseUrl()."/visit/add?id=".$this->patID."'>Add New Visit</a>"
?>
    <a href="javascript:history.back();" class="btn btn-default"> << Back</a>
    </div>
    <div class="col-md-2 column"></div>
    
