<br /><br />
<div id="view-content">
	<p>View script for controller <b>DiseaseHistory</b> and script/action name <b>edit</b></p>
</div>
<form action="" method="post">
<?php
    echo $this->diseaseHistoryForm->id.
            $this->diseaseHistoryForm->disease.
            $this->diseaseHistoryForm->patient.
            $this->diseaseHistoryForm->date.
            $this->diseaseHistoryForm->update;
?>
</form>