<style>
    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-color: #0398CA;
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }
    
    .about_t {
        background-color: #22475E;
    }
    
    .about_t a{
        color: white;
    }
</style>

<div id="welcome">
    <h1>Welcome to the <span id="zf-name">Nubia Project :)</span></h1>
    <h2>Team Member : </h2>
    <h3>- Ashraf Ismail</h3>
    <h3>- Antonois Mounir</h3>
    <h3>- Esraa Elsayed</h3>
    <h3>- Omar Elsayed</h3>
    <h3>- Salma Helmy</h3>
</div>