<br>
<div class="right_header">
        Administration Tools
</div>
<br><br><br>
<div style='font-size: 20px'>
    
    <table>
        <tr>
            <td>
                <ul>
                    <li>
                        <b>Manage Database : </b>
                    </li><br/>

                    <li>
                        <a href="<?= $this->baseUrl() ?>/Radiation">Radiations</a>                                           
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Vital">Vitals</a>             
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Test">Tests</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Medicaiton">Medications</a>                                           
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Disease">Diseases</a>             
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Surgery">Surgeries</a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <b>Manage Groups : </b>
                    </li><br/>

                    <li>
                        <a href="<?= $this->baseUrl() ?>/physiciangroup">Physicians Groups</a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <b>Manage Entities : </b>
                    </li><br/>

                    <li>
                        <a href="<?= $this->baseUrl() ?>/patient">Patients</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/physician">Physicians</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/user">Users</a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <b>Manage Patient Results : </b>
                    </li><br/>

                    <li>
                        <a href="<?= $this->baseUrl() ?>/Radiationresult">Radiation Results</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Vitalresult">Vital Results</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Testresult">Test Results</a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <b>Urgent Links : </b>
                    </li><br/>

                    <li>
                        <a href="<?= $this->baseUrl() ?>/patient/search">Search Patients</a>                                           
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/physician/search">Search Physicians</a>             
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Test">Search Clinicians</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/user/add">Add User</a>                                           
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/visit/add">Create Visit</a>             
                    </li>
                </ul>
            </td>
        </tr>
        <tr>
            <td>
                <ul>
                    <li>
                        <b>Manage Patient History : </b>
                    </li><br/>
                    
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Medicationhistory">Medication History</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Surgeryhistory">Surgery History</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/Diseasehistory">Disease History</a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <b>Manage Patient Visits : </b>
                    </li><br/>
                    
                    <li>
                        <a href="<?= $this->baseUrl() ?>/visit">Visit Requests</a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <b>Manage Themes : </b>
                    </li><br/>

                    <li>
                        <a href="#">Future Work</a>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li>
                        <b>ACL Security : </b>
                    </li><br/>

                    <li>
                        <a href="<?= $this->baseUrl() ?>/permissions">Resources Permission</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/permissions/edit">Edit Resources Permissions</a>
                    </li>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/permissions/generateresources">Generate Resources </a>
                    </li>
                </ul>
            </td>
        </tr>
        <tr></tr>
        <tr></tr>
    </table>
</div>
