<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-color: #0398CA;
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }
</style>
<table>
    <tr>
        <td>
            <div id="welcome">
                <h1>Welcome to the <span id="zf-name">Nubia Project :)</span></h1>
                <h2>Team Member : </h2>
                <h3>- Ashraf Ismail</h3>
                <h3>- Antonois Mounir</h3>
                <h3>- Esraa Elsayed</h3>
                <h3>- Omar Elsayed</h3>
                <h3>- Salma Helmy</h3>
            </div>
        </td>
        <td>
            <h1>Administration Tools: </h1>
            <table>
                <tr>
                    <td>
                        <ul>
                            <li>
                                <b>Medical Tools : Omar</b>
                            </li>
                            <li>
                                <a href="<?= $this->baseUrl() ?>/Radiation">Radiations</a>
                                <ul>
                                    <li><a href="<?= $this->baseUrl() ?>/Radiation-Result">Radiation Result</a></li>
                                </ul>                           
                            </li>
                            <li>
                                <a href="<?= $this->baseUrl() ?>/Vital">Vitals</a>
                                <ul>
                                    <li><a href="<?= $this->baseUrl() ?>/Vital-Result">Vital Result</a></li>
                                </ul>  
                            </li>
                            <li>
                                <a href="<?= $this->baseUrl() ?>/Test">Tests</a>
                                <ul>
                                    <li><a href="<?= $this->baseUrl() ?>/Test-Result">Test Result</a></li>
                                </ul>  
                            </li>
                        </ul>
                    </td>
                    <td>
                        <ul>
                            <li>
                                <b>Medical History : Tony </b>
                            </li>
                            <li>
                                <a href="#">Diseases</a>
                            </li>
                            <li>
                                <a href="#">Surgerys</a>
                            </li>
                            <li>
                                <a href="#">Drugs</a>
                            </li>
                        </ul>
                    </td>
                    <td>
                        <ul>
                            <li>
                                <b>Other : </b>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td>
                        <ul>
                            <li>
                                <b>Other : </b>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                        </ul>
                    </td>
                    <td>
                        <ul>
                            <li>
                                <b>Other : </b>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                        </ul>
                    </td>
                    <td>
                        <ul>
                            <li>
                                <b>Other : </b>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                            <li>
                                <a href="#">Other</a>
                            </li>
                        </ul>
                    </td>
                </tr>
                <tr></tr>
                <tr></tr>
            </table>
        </td>
    </tr>
</table>
