<script>

$(document).ready(function() {

var date = new Date();
var d = date.getDate();
var m = date.getMonth();
var y = date.getFullYear();

$('#calendar').fullCalendar({
    header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
    },
    editable: false,
    events: <?= $this->acceptedvisitJ  ?>,
    eventClick: function(event) {
        // opens events in a popup window
      //  window.open(event.url, 'gcalevent', 'width=600,height=600');
        if(isInArray(event.id,responseid)){
        window.location = event.url;
            }
            else{
                event.url = "patient/showprofile/patientId/"+event.patid;
                window.location = event.url;
               // document.getElementById('"'+event.id+'"').cssText='{"background-color":"green"}';
            }
        
        
        return false;
    }
            
    
    
   
    
    
   
    
});

});

</script>
<style>

	#calendar {
		width: 900px;
		margin: 0 auto;
		}
		
	#wrap {
		width: 1100px;
		margin: 0 auto;
		}
		
	#external-events {
		float: left;
		width: 150px;
		padding: 0 10px;
		border: 1px solid #ccc;
		background: #eee;
		text-align: left;
		}
		
	#external-events h4 {
		font-size: 16px;
		margin-top: 0;
		padding-top: 1em;
		}
		
	.external-event { /* try to mimick the look of a real event */
		margin: 10px 0;
		padding: 2px 4px;
		background: #cccccc;
		color: #fff;
		font-size: .85em;
		cursor: pointer;
		}
		
	#external-events p {
		margin: 1.5em 0;
		font-size: 11px;
		color: #666;
		}
		
	#external-events p input {
		margin: 0;
		vertical-align: middle;
		}

	#calendar {
		float: right;
		width: 900px;
		}

</style>
<style>
    #penrequests{ 
        top: -8px;
        left: 27px;
        position: relative;
        font-weight: bold;
    }
    
    .pendiv
    {
        border-top: solid 1px;
    } 
</style>
<div id='wrap'>

    <div id='external-events' style="width: 198px;top: 20px;position: relative">
        <h4 id="penrequests">Pending Visits</h4>
        <?php
            if($this->pen)
            {
                foreach ($this->pen as $penvisit) {      
                    ?>
                    <div class="pendiv">
                        <form method="GET" action="<?= $this->baseUrl();?>/physicianvisit/accept">
                            <a href="patient/showprofile/patientId/<?= $penvisit['patient_id']?>"> <p title="Description"> <?= $penvisit["description"] ?></p></a>
                            <p>  <?= $penvisit["date"] ?></p>
                            <input type="date" name="created_date" min="<?= $penvisit["date"] ?>" required>
                            <input type="time" name="created_time"   required>
                            <input type="hidden" value="<?= $penvisit['id'] ?>" name="vid">
                            <input type="hidden" value="<?= $this->phyId ?>" name="pid">
                            <input type="submit" value="Accept" style="position: relative;left:-4px;top:0px;">
                      </form>
                    </div>

                    <?php
                }
            }
        ?>
    </div>

    <div id='calendar'></div>
    <div style='clear:both'></div>
</div>

<script>
    document.getElementsByClassName("content")[0].style.float = 'left';
</script>
<script>
    var responseid = 0;
function checkAvailable() {
        var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {
            if(xhr.readyState === 4) {
           
                if(isNotZero(this.responseText)) {
                    responseid = json2array(JSON.parse(this.responseText));
                    console.log(responseid);
                 
                
                }
            }
        };

        xhr.open("get","<?=$this->baseUrl()?>/vid.json");
        xhr.send();
    }
    
      window.onload = setInterval(function(){
                                    checkAvailable();
                                },2000); 
       window.onload = setInterval(function(){
                                    changeColor(responseid);
                                },500);                            
                                
      function isInArray(value, array) {
          flag = false;
        for (index = 0; index < array.length; ++index) {
    if(array[index] == value)
    {
        flag = true;
    }
}
return flag;
  
}

 function isNotZero(array) {
          flag = false;
          
        for (index = 0; index < array.length; ++index) {
    if(array[index] !== 0)
    {
        flag = true;
    }
}
return flag;
  
}
 var switcher=0;
function changeColor(array) {
         
        for (index = 0; index < array.length; ++index) {
          if(switcher==0){  
    $("a[href*='vid/"+array[index]+"']").css({"background-color":"red"});
          }else{
               $("a[href*='vid/"+array[index]+"']").css({"background-color":"green"});
          }
}
if(switcher==0){switcher=1;}else{switcher=0;}

  
}
function json2array(json){
    var result = [];
    var keys = Object.keys(json);
    keys.forEach(function(key){
        result.push(json[key]);
    });
    return result;
}
    </script>
    <script>
  $(function() {
    $( document ).tooltip();
  });
  </script>
  <style>
  label {
    display: inline-block;
    width: 5em;
  }
  </style>
