<style type="text/css">
    .list {
        display: inline-block;
        list-style-type:none;
    }
</style>

<span class="label label-primary" style="font-size: 27px;">Administration Tools</span>
<br><br><br>
    
    <ul class="list">
        <li>
            <ul>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                      <h3 class="panel-title">Manage Database :</h3>
                    </div>
                    <div class="panel-body">
                      <a href="<?= $this->baseUrl() ?>/Radiation">Radiations</a> 
                    </div>
                    <div class="panel-body">
                      <a href="<?= $this->baseUrl() ?>/Vital">Vitals</a>
                    </div>
                    <div class="panel-body">
                      <a href="<?= $this->baseUrl() ?>/Test">Tests</a>
                    </div>
                    <div class="panel-body">
                      <a href="<?= $this->baseUrl() ?>/Medicaiton">Medications</a>  
                    </div>
                    <div class="panel-body">
                      <a href="<?= $this->baseUrl() ?>/Disease">Diseases</a> 
                    </div>
                    <div class="panel-body">
                      <a href="<?= $this->baseUrl() ?>/Surgery">Surgeries</a>
                    </div>
                  </div>
            </ul>
        </li>
        <li>
            <ul>
                <div class="panel panel-warning">
                    <div class="panel-heading">
                      <h3 class="panel-title">Manage Groups </h3>
                    </div>
                    <div class="panel-body">
                      <a href="<?= $this->baseUrl() ?>/physiciangroup">Physicians Groups</a>
                    </div>
                    <div class="panel-body">
                      <a href="<?= $this->baseUrl() ?>/roles">User Roles</a>
                    </div>
                  </div>
            </ul>
        </li>
    </ul>
    <ul class="list">
        <li>
            <div class="panel panel-info">
                <div class="panel-heading">
                  <h3 class="panel-title">Manage Entities </h3>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/patient">Patients</a>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/physician">Physicians</a>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/user">Users</a>
                </div>
              </div>
        </li>
        <li>
            <div class="panel panel-success">
                <div class="panel-heading">
                  <h3 class="panel-title">Manage Patient Results </h3>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/Radiationresult">Radiation Results</a>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/Vitalresult">Vital Results</a>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/Testresult">Test Results</a>
                </div>
              </div>
        </li>
    </ul>
    <ul class="list">
        <li>
            <div class="panel panel-info">
                <div class="panel-heading">
                  <h3 class="panel-title">Manage Patient Visits </h3>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/visit">Visit Requests</a>
                </div>
              </div>
        </li>
        <li>
            <div class="panel panel-warning">
                <div class="panel-heading">
                  <h3 class="panel-title">Manage Patient History </h3>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/Medicationhistory">Medication History</a>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/Surgeryhistory">Surgery History</a>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/Diseasehistory">Disease History</a>
                </div>
            </div>
        </li>
    </ul>
    <ul class="list">
        <li>
            <div class="panel panel-success">
                <div class="panel-heading">
                  <h3 class="panel-title">Urgent Links </h3>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/patient/search">Search Patients</a>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/user/search">Search Users</a>    
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/user/add">Add User</a> 
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/visit/add">Create Visit</a>    
                </div>
              </div>
        </li>
        <li>
            <div class="panel panel-danger">
                <div class="panel-heading">
                  <h3 class="panel-title">ACL Security </h3>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/permissions">Resources Permission</a>
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/permissions/edit">Edit Resources Permissions</a>  
                </div>
                <div class="panel-body">
                  <a href="<?= $this->baseUrl() ?>/permissions/generateresources">Generate Resources </a>
                </div>
              </div>
        </li>
    </ul>
        

