<h1>Vitals :</h1>
<h2>Vitals Statistics</h2>
<ul>
    <li>
        <b>Number of Vitals : <?= $this->vitalsStatistics['count'] ?></b>
    </li>
    <li>
        <b>Last Inserted Vital : --------</b>
    </li>
    <li>
        <b>Last Updated Vital : --------</b>
    </li>
</ul>

<ul>
    <li><a href="<?= $this->baseUrl() ?>/Vital/add">Add Vital</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Vital/view">View Vital</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Vital/delete">Delete Vital</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Vital/edit">Edit Vital</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Vital/search">Search Vital</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Vital/list">List Vitals</a></li>

</ul>
