<div class="row clearfix">
    <div class="col-md-2 column"></div>
    <div class="col-md-5 column">
        <span class="label label-primary" style="font-size: 25px">Vital List</span>
        <br><br>
	<?php
            if ($this->vitals) {
                $vital = $this->vitals;
                echo "<table class='table table-striped table-hover'>";
                echo "<thead><tr><th>Name</th><th>Action</th></tr></thead>";
                foreach ($this->paginator as $vital) {
                    echo "<tr>";
                    echo "<td>".$vital['name']."</td>";
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Vital/view?id=".$vital['id']."' class='btn btn-info'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Vital/edit?id=".$vital['id']."' class='btn btn-default'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Vital/delete?id=".$vital['id']."' class='btn btn-default'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
                echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
            }
            else {
                echo "<h2> No, Vitals !!</h2>";
                echo "but you can <a href='".$this->baseUrl()."/Vital/add' >Add Vital</a> ";
            }
        ?>
        <br>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
    <div class="col-md-2 column"></div>
</div>
