<div class="row clearfix">
    <div class="col-md-8 column">
        <span class="label label-primary" style="font-size: 25px">Vital view</span><br><br>
        <br><br>
<?php
    if($this->vital) {
        ?> 
        <label style="font-size:20px">Name :&nbsp;</label>
        <label style="font-size:15px"><?= $this->vital[0]['name'] ?></label><br><br>
            <a href="<?= $this->baseUrl() ?>/Vital/edit?id=<?= $this->vital[0]['id'] ?>" class='btn btn-default'>Edit </a>
            <a href="<?= $this->baseUrl() ?>/Vital/delete?id=<?= $this->vital[0]['id'] ?>" class='btn btn-default'>Delete </a>
        <?php
    }
    else {
        ?><h2>Not Found !!</h2><?php
    }
?>
    <br><br>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
    <div class="col-md-2 column"></div>
</div>
