<br /><br />
<div id="view-content">
    <h1>Test List : </h1>
	<?php
            if ($this->tests) {
                echo "<table>";
                echo "<tr><th>Name</th><th>Action</th></tr>";
                foreach ($this->radiations as $radiation) {
                    echo "<tr>";
                    echo "<td>".$radiation['name']."</td>";
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Test/view?id=".$radiation['id']."'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Test/edit?id=".$radiation['id']."'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Test/delete?id=".$radiation['id']."'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2> No, Tests !!</h2>";
                echo "but you can <a href='".$this->baseUrl()."/Test/add' >Add Test</a> ";
            }
        ?>
</div>