
    <h1>Test List : </h1>
	<?php
            if ($this->tests) {
                $test = $this->tests;
                echo "<table>";
                echo "<tr><th>Name</th><th>Action</th></tr>";
                foreach ($this->paginator as $test) {
                    echo "<tr>";
                    echo "<td>".$test['name']."</td>";
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Test/view?id=".$test['id']."'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Test/edit?id=".$test['id']."'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Test/delete?id=".$test['id']."'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
                echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
            }
            else {
                echo "<h2> No, Tests !!</h2>";
                echo "but you can <a href='".$this->baseUrl()."/Test/add' >Add Test</a> ";
            }
        ?>
