<div class="row clearfix">
    <div class="col-md-2 column"></div>
    <div class="col-md-6 column">
        <span class="label label-primary" style="font-size: 25px">Test List</span>
        <br><br>
        <?php
        if ($this->tests) {
            $test = $this->tests;
            echo "<table class='table table-striped table-hover'>";
            echo "<thead><tr><th>Name</th><th>Action</th></tr></thead>";
            foreach ($this->paginator as $test) {
                echo "<tr>";
                echo "<td>".$test['name']."</td>";
                echo "<td>";
                echo "<a href='". $this->baseUrl()."/Test/view?id=".$test['id']."' class='btn btn-info'> View </a>";
                echo "<a href='". $this->baseUrl()."/Test/edit?id=".$test['id']."' class='btn btn-default'> Edit </a>";
                echo "<a href='". $this->baseUrl()."/Test/delete?id=".$test['id']."' class='btn btn-default'> Delete </a>";
                echo "</td>";
                echo "</tr>";
            }
            echo "</table>";
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
        }
        else {
            echo "<h2> No, Tests !!</h2>";
            echo "but you can <a href='".$this->baseUrl()."/Test/add' >Add Test</a> ";
        }
    ?>
        <br>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
    <div class="col-md-2 column"></div>
</div>
