
    <h2>Test Search : </h2>
    <b>Search Key</b>
    <form action="search" method="GET">
        <input type="text" id="key" name="key" placeholder="Enter search key"/>
        <input type="submit" value="Search"/>
    </form>
    <?php
        if( $this->key ) {
            echo "<script>document.getElementById('key').value = '".$this->key."'; </script>";
            if ($this->tests) {
                echo "<table>";
                echo "<tr><th>Name</th><th>Action</th></tr>";
                foreach ($this->tests as $test) {
                    echo "<tr>";
                    echo "<td>".$test['name']."</td>";
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Test/view?id=".$test['id']."'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Test/edit?id=".$test['id']."'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Test/delete?id=".$test['id']."'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2>Not Found !!</h2>";
            }
        }    
    ?>
