<br /><br />
<div id="view-content">
	<?= $this->form; ?>
    <a href="javascript:history.back();">Back</a>
</div>

<script>
    function addFile() {
        container = document.getElementById("file-element");
        file = document.createElement("input");
        file.setAttribute("name","file[]");
        file.setAttribute("type","file");
        
        container.appendChild(file);      
    }
</script>