<div class="row clearfix">
    <div class="col-md-8 column">
        <span class="label label-success" style="font-size: 20px">Radiation results</span>
        <span class="label label-success" style="font-size: 15px">Radiation results Statistics</span>
        <ul class="list-group">
            <li class="list-group-item">
              <span class="badge"><?= $this->radiationResultsStatistics['count'] ?></span>
              Number of Radiation results :
            </li>
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Added Radiation result :
            </li>
          </ul>

        <div class="btn-group btn-group-justified">
            <a href="<?= $this->baseUrl() ?>/Radiationresult/add" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/add.png" style="width: 15px;margin-right: 5px">Add Radiation result</a>
        <a href="<?= $this->baseUrl() ?>/Radiationresult/search" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/search.png" style="width: 15px;margin-right: 5px">Search Radiation results</a>
        <a href="<?= $this->baseUrl() ?>/Radiationresult/list" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/list.png" style="width: 15px;margin-right: 5px">List Radiation results</a>
        </div>
        <br><br>
        <a href="javascript:history.back();" class="btn btn-default">Back</a>    
    </div>
    <div class="col-md-2 column"></div>
</div>
