<br />
<div id="view-content">
    <h1>Radiation-Results :</h1>
    <h2>Radiation-Results Statistics</h2>
    <ul>
        <li>
            <b>Number of Radiation-Results : <?= $this->radiationResultsStatistics['count'] ?></b>
        </li>
        <li>
            <b>Last Inserted Radiation-Result : --------</b>
        </li>
        <li>
            <b>Last Updated Radiation-Result : --------</b>
        </li>
    </ul>
  
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/Radiationresult/add">Add Radiation-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Radiationresult/view">View Radiation-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Radiationresult/delete">Delete Radiation-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Radiationresult/edit">Edit Radiation-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Radiationresult/search">Search Radiation-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Radiationresult/list">List Radiation-Results</a></li>
        
    </ul>
</div>