<div class="row clearfix">
    <div class="col-md-2 column"></div>
    <div class="col-md-8 column">
        <span class="label label-success" style="font-size: 20px">Radiationresults</span>
        <span class="label label-success" style="font-size: 15px">Radiationresults Statistics</span>
        <ul class="list-group">
            <li class="list-group-item">
              <span class="badge"><?= $this->radiationResultsStatistics['count'] ?></span>
              Number of Radiationresults :
            </li>
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Joined Radiationresult :
            </li>
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Joined Radiationresult :
            </li>
          </ul>

        <div class="btn-group btn-group-justified">
            <a href="<?= $this->baseUrl() ?>/Radiationresult/add" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/add.png" style="width: 15px;margin-right: 5px">Add Radiationresult</a>
        <a href="<?= $this->baseUrl() ?>/Radiationresult/search" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/search.png" style="width: 15px;margin-right: 5px">Search Radiationresults</a>
        <a href="<?= $this->baseUrl() ?>/Radiationresult/list" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/list.png" style="width: 15px;margin-right: 5px">List Radiationresults</a>
        </div>
        <br><br>
        <a href="javascript:history.back();" class="btn btn-default">Back</a>    
    </div>
    <div class="col-md-2 column"></div>
</div>
