
    <h1>Radiation-Result List : </h1>
	<?php
            if ($this->radiationResults) {
                echo "<table>";
                echo "<tr><th>Visit Request</th><th>Radiation</th><th>Data</th><th>Action</th></tr>";
                foreach ($this->radiationResults as $radiationResult) {
                    echo "<tr>";
                    echo "<td>".$radiationResult['visit_request_id']."</td>";
                    echo "<td>".$radiationResult['radiationName']."</td>";
                    if($radiationResult['radiation_data']) {
                        echo "<td>".$radiationResult['radiation_data']."</td>";
                    }
                    else {
                        echo "<td>Pending</td>";
                    }    
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/view?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/edit?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/delete?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2> No, Radiation-Results !!</h2>";
                echo "but you can <a href='".$this->baseUrl()."/Radiation-Result/add' >Add Radiation-Result</a> ";
            }
        ?>