<div class="well be-component">
    <form action="search" method="GET" class="form-horizontal">
        <fieldset>
          <legend><i class="fa fa-stethoscope fa-fw"></i>Radiation Search </legend>
          <div class="form-group">
              <div class="col-lg-5">
                  <select name="requestId" id="requestId" class='form-control'>
                      <option value="">Choose Visit</option>
                      <?php
                          foreach ($this->requests as $request) {
                              echo "<option value='".$request['id']."'>".$request['date']."</option>";
                          }
                      ?>
                  </select>
              </div>
          </div>
          <div class="form-group">
              <div class="col-lg-5">
                  <input type="submit" value="Search" class='btn btn-primary'/>
              </div>
          </div>
        </fieldset>
    </form>
</div>
<a href="javascript:history.back();" class="btn btn-default">Back</a> 
    <?php
        if($this->requestId) {
            echo "<script>document.getElementById('requestId').value = '".$this->requestId."'; </script>";
            if ($this->radiationResults) {
                echo "<table>";
                echo "<tr><th>Visit Request</th><th>Radiation</th><th>Data</th><th>Action</th></tr>";
                foreach ($this->radiationResults as $radiationResult) {
                    echo "<tr>";
                    echo "<td>".$radiationResult['visit_request_id']."</td>";
                    echo "<td>".$radiationResult['radiationName']."</td>";
                    
                    if($radiationResult['data']) {
                        ?><td><?= $radiationResult['data'] ?></td><?php
                    }
                    else {
                        ?><td>Pending</td><?php
                    }
                    
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/view?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/edit?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/delete?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2>Not Found !!</h2>";
            }
        }
        
    
    ?>
