<br /><br />
<div id="view-content">
    <h2>Radiation Search : </h2>
    <b>Search Key</b>
    <form action="search" method="GET">
        <select name="requestId" id="requestId">
            <option value="">Choose Visit</option>
            <?php
                foreach ($this->requests as $request) {
                    echo "<option value='".$request['id']."'>".$request['date']."</option>";
                }
            ?>
        </select>
        <input type="submit" value="Search"/>
    </form>
    <?php
        if($this->requestId) {
            echo "<script>document.getElementById('requestId').value = '".$this->requestId."'; </script>";
            if ($this->radiationResults) {
                echo "<table>";
                echo "<tr><th>Visit Request</th><th>Radiation</th><th>Data</th><th>Action</th></tr>";
                foreach ($this->radiationResults as $radiationResult) {
                    echo "<tr>";
                    echo "<td>".$radiationResult['visit_request_id']."</td>";
                    echo "<td>".$radiationResult['radiationName']."</td>";
                    
                    if($radiationResult['data']) {
                        ?><td><?= $radiationResult['data'] ?></td><?php
                    }
                    else {
                        ?><td>Pending</td><?php
                    }
                    
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/view?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/edit?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Radiation-Result/delete?radId=".$radiationResult['radiation_id']."&reqId=".$radiationResult['visit_request_id']."'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2>Not Found !!</h2>";
            }
        }
        
    
    ?>
</div>