<br /><br />
<div id="view-content">
	<p>View script for controller <b>Medication</b> and script/action name <b>search Medication</b></p>
</div>
<form action="" method="post">
        <input type="text" name="medicationName" placeholder="Enter search .. "/>
        <input type="submit" value="Search"/>
</form>

 <?php
if ($this->medications) {
    echo "<table>";
    echo "<tr><th>Name</th><th>Action</th></tr>";
    foreach ($this->medications as $medication) {
        echo "<tr>";
        echo "<td>".$medication["name"]."</td>";
        echo "<td>";
        echo "<a href='". $this->baseUrl()."/medication/view?id=".$medication["id"]."'> View </a>";
        echo "<a href='". $this->baseUrl()."/medication/edit?id=".$medication["id"]."'> Edit </a>";
        echo "<a href='". $this->baseUrl()."/medication/delete?id=".$medication["id"]."'> Delete </a>";
        echo "</td>";
        echo "</tr>";
    }
    echo "</table>";
}
else {
    echo "<h2>Not Found !!</h2>";
}   
?>