<ul class="pagination pagination-sm">


        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
        <li> <a href="<?= $this->url(array('page' => $this->first)); ?>">Start</a></li>
        <?php else: ?>
        <li class="disabled"><a>Start</a></li>
        <?php endif; ?>
    
        <!-- Previous page link -->
    
        <?php if (isset($this->previous)): ?>
        <li><a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a></li>
        <?php else: ?>
        <li class="disabled"><a>&lt; Previous</a></li>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
        <li><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a></li>
            <?php else: ?>
        <li class="active"><a><?= $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
        <li><a href="<?= $this->url(array('page' => $this->next)); ?>">Next &gt;</a></li>
        <?php else: ?>
        <li class="disabled"><a>Next &gt;</a></li>
        <?php endif; ?>
        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
        <li><a href="<?= $this->url(array('page' => $this->last)); ?>">End</a></li>
        <?php else: ?>
        <li class="disabled"><a>End</a></li>
        <?php endif; ?>
        <li class="disabled"><a>&nbsp; Page <?= $this->current; ?> of <?= $this->last; ?></a></li>
   </ul>
