<br /><br />
<div class="right_header">
    <a href="<?= $this->baseUrl() ?>/Roles" class="logo_link">Roless</a>
</div>
<h2>Roless Statistics</h2>
<ul>
    <li>
        <b>Number of Roless : <?= $this->radiationsStatistics['count'] ?></b>
    </li>
    <li>
        <b>Last Inserted Roles : --------</b>
    </li>
    <li>
        <b>Last Updated Roles : --------</b>
    </li>
</ul>

<ul>
    <li><a href="<?= $this->baseUrl() ?>/Roles/add">Add Roles</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Roles/view">View Roles</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Roles/delete">Delete Roles</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Roles/edit">Edit Roles</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Roles/list">List Roless</a></li>

</ul>