<div class="row clearfix">
    <div class="col-md-8 column">
        <span class="label label-success" style="font-size: 20px">Roles</span><br><br>
        <span class="label label-success" style="font-size: 15px">Roles Statistics</span>
        <ul class="list-group">
            <li class="list-group-item">
              <span class="badge">14</span>
              Number of Roles :
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Added Role :
            </li>
          </ul>

        <div class="btn-group btn-group-justified">
            <a href="<?= $this->baseUrl() ?>/Roles/add" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/add.png" style="width: 15px;margin-right: 5px">Add Role</a>
            <a href="<?= $this->baseUrl() ?>/Roles/list" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/list.png" style="width: 15px;margin-right: 5px">List Roles</a>
        </div>
        <br><br>
        <a href="javascript:history.back();" class="btn btn-default">Back</a>    
    </div>
    <div class="col-md-2 column"></div>
</div>
