<div class="row clearfix">
    <div class="col-md-6 column">
        <span class="label label-primary" style="font-size: 25px">Radiation List</span>
        <br><br>
<?php
    if ($this->roles) {
        echo "<table class='table table-striped table-hover'>";
        echo "<thead><tr><th>Name</th><th>Action</th></tr></thead>";
        foreach ($this->roles as $role) {
            echo "<tr>";
            echo "<td>".$role['name']."</td>";
            echo "<td>";
            echo "<a href='". $this->baseUrl()."/Roles/view?id=".$role['id']."' class='btn btn-info'> View </a>";
            echo "<a href='". $this->baseUrl()."/Roles/edit?id=".$role['id']."' class='btn btn-default'> Edit </a>";
            echo "<a href='". $this->baseUrl()."/Roles/delete?id=".$role['id']."' class='btn btn-default'> Delete </a>";
            echo "</td>";
            echo "</tr>";
        }
        echo "</table>";
    }
    else {
        echo "<h2> No, Roles !!</h2>";
        echo "but you can <a href='".$this->baseUrl()."/Roles/add' >Add Roles</a> ";
    }
?>
 <br>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
    <div class="col-md-2 column"></div>
</div>