<div class="row clearfix">
    <span class="label label-primary" style="font-size: 25px">Add Surgery</span>
    <br><br>
    <form class="form-horizontal" method="post">
  <fieldset>
        <div class="form-group">
          <div class="col-lg-5">
              <?= $this->addSurgeryForm->operation?>
          </div>
        </div> 
        <div class="form-group">
           <div class="col-lg-5 col-lg-offset-0">
               <?= $this->addSurgeryForm->add?>
           </div>
         </div>
  </fieldset>
</form>      
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
</div> 
