<br /><br />
<div class="right_header">
    <a href="<?= $this->baseUrl() ?>/Surgery" class="logo_link">Surgeries</a>
</div>
<h2>Surgeries Statistics</h2>
<ul>
    <li>
        <b>Number of Surgeries : <?= $this->surgeryStatistics['count'] ?></b>
    </li>
    <li>
        <b>Last Inserted Surgery : --------</b>
    </li>
    <li>
        <b>Last Updated Surgery : --------</b>
    </li>
</ul>

<ul>
    <li><a href="<?= $this->baseUrl() ?>/Surgery/add">Add Surgery</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Surgery/delete">Delete Surgery</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Surgery/edit">Edit Surgery</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Surgery/search">Search Surgery</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Surgery/list">List Surgeries</a></li>

</ul>