<div class="row clearfix">
    <div class="col-md-2 column"></div>
    <div class="col-md-6 column">
        <span class="label label-primary" style="font-size: 25px">Surgeries List</span>
        <br><br>
        <?php
        if ($this->surgeries) {
            $surgery = $this->surgeries;
            echo "<table class='table table-striped table-hover'>";
            echo "<thead><tr><th>Name</th><th>Action</th></tr></thead>";
            foreach ($this->paginator as $surgery) {
                echo "<tr>";
                echo "<td>".$surgery['operation']."</td>";
                echo "<td>";
                echo "<a href='". $this->baseUrl()."/surgery/edit?id=".$surgery['id']."' class='btn btn-default'> Edit </a>";
                echo "<a href='". $this->baseUrl()."/surgery/delete?id=".$surgery['id']."' class='btn btn-default'> Delete </a>";
                echo "</td>";
                echo "</tr>";
            }
            echo "</table>";
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
        }
        else {
            echo "<h2> No, Surgeries !!</h2>";
            echo "but you can <a href='".$this->baseUrl()."/Surgery/add' >Add Surgery</a> ";
        }
    ?>
        <br>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
    <div class="col-md-2 column"></div>
</div>