
<form action="" method="post">
        <input type="text" name="operation" placeholder="Enter search .. "/>
        <input type="submit" value="Search"/>
</form>

 <?php
if ($this->surgeries) {
    echo "<table>";
    echo "<tr><th>Name</th><th>Action</th></tr>";
    foreach ($this->surgeries as $surgery) {
        echo "<tr>";
        echo "<td>".$surgery["name"]."</td>";
        echo "<td>";
        echo "<a href='". $this->baseUrl()."/surgery/view?id=".$surgery["id"]."'> View </a>";
        echo "<a href='". $this->baseUrl()."/surgery/edit?id=".$surgery["id"]."'> Edit </a>";
        echo "<a href='". $this->baseUrl()."/surgery/delete?id=".$surgery["id"]."'> Delete </a>";
        echo "</td>";
        echo "</tr>";
    }
    echo "</table>";
}
else {
    echo "<h2>Not Found !!</h2>";
}   
?>