<link href="<?= $this->baseUrl() ?>/css/tableStyle.css" rel="stylesheet">
<style type="text/css" >
    body {
        background: url(<?= $this->baseUrl() ?>/imgs/background.jpg);
	margin:0 auto;
    }
    
    .header{
        height: 45px;
        background-color:  rgb(236, 172, 90);
    }
    
    .content {
        margin: 10px;
    }
    
    .logo {
        margin-left: 150px;
        padding-top: 5px;
        font-size: 25;
        display: inline;
    }
    
    .logo_link {
        color: black;
    }
    
    .logo_link:active,
    .logo_link:hover {
        text-decoration: none;
        color: black;
    }
    
    .info-panel{
        float: right;
        margin-right: 50px;
        padding-top: 10px;
        display: inline;
    }
    
    .welcome {
        display: inline-block;
        height: 26px;
        background-color: beige;
        padding: 2px;
        border-radius: 30;
    }
    
    .welcome_text {
        padding-right: 10px;
        padding-left: 10px;
    }
    
    .mainmenu {
        display: inline-block;
        font-size: 16;
        padding-right: 20px;
    }
    
    .menu {
        height: 45px;
        background-color:  rgb(123, 126, 123);
    }
    
    .main_links {
        padding-top: 9px;
        color: white;
        font-size: 17px;
    }
    
    .main_link {
        color: white;
    }
    
    .main_link:active,
    .main_link:hover {
        text-decoration: none;
        color: white;
    }
    
    .urgent {
        background-color: lightgray;
        height: 31px;
        width: 113px;
        position: absolute;
        padding-left: 14px;
        padding-bottom: 21px;
        padding-top: 5px;
        top: 51px;
        font-size: 17px;
        border-radius: 2px;
    }
    
    .caution {
        margin-top: 154px;
        font-size: 35px;
    }
    
    .hint {
        font-size: 19px;
    }
    
    .right_header {
        background-color: rgb(240, 180, 100);
        padding-left: 19px;
        font-size: 26px;
        display: inline;
        padding-right: 21px;
        padding-top: 6px;
        padding-bottom: 6px;
        border-radius: 4px;
        border-left-width: 16px;
        border-left-style: solid;
        border-left-color: rgb(139, 136, 136);
    }

    .greyButton {
            background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #ebebeb), color-stop(1, #d1cfd1));
            background:-moz-linear-gradient(top, #ebebeb 5%, #d1cfd1 100%);
            background:-webkit-linear-gradient(top, #ebebeb 5%, #d1cfd1 100%);
            background:-o-linear-gradient(top, #ebebeb 5%, #d1cfd1 100%);
            background:-ms-linear-gradient(top, #ebebeb 5%, #d1cfd1 100%);
            background:linear-gradient(to bottom, #ebebeb 5%, #d1cfd1 100%);
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#ebebeb', endColorstr='#d1cfd1',GradientType=0);
            background-color:#ebebeb;
            -moz-border-radius:28px;
            -webkit-border-radius:28px;
            border-radius:28px;
            border:1px solid #d4d4d4;
            display:inline-block;
            cursor:pointer;
            color:#696969;
            font-family:arial;
            font-size:15px;
            padding:4px 21px;
            text-decoration:none;
            text-shadow:0px 0px 0px #adadad;
    }
    .greyButton:hover {
            background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #d1cfd1), color-stop(1, #ebebeb));
            background:-moz-linear-gradient(top, #d1cfd1 5%, #ebebeb 100%);
            background:-webkit-linear-gradient(top, #d1cfd1 5%, #ebebeb 100%);
            background:-o-linear-gradient(top, #d1cfd1 5%, #ebebeb 100%);
            background:-ms-linear-gradient(top, #d1cfd1 5%, #ebebeb 100%);
            background:linear-gradient(to bottom, #d1cfd1 5%, #ebebeb 100%);
            filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#d1cfd1', endColorstr='#ebebeb',GradientType=0);
            background-color:#d1cfd1;
    }
    .greyButton:active {
            position:relative;
            top:1px;
    }
    
    input {
        border: none;
        border-radius: 20px;
        padding: 5px 8px;
        color: #333;
        box-shadow: 
            inset 0 2px 0 rgba(0,0,0,.2), 
            0 0 4px rgba(0,0,0,0.1);
    }

    input:focus {
        outline: none;
        box-shadow: 
            inset 0 2px 0 rgba(0,0,0,.2), 
            0 0 4px rgba(0,0,0,0.1), 
            0 0 5px 1px #51CBEE;
    }


    
    

</style>

<?php
    $baseUrl = $this->baseUrl();
        $userType = "Guest";
        $authorization = Zend_Auth::getInstance();
        if ($authorization->hasIdentity()) {
            $authInfo = $authorization->getIdentity();
            $userType = $authInfo['userType'];
        }
?>

<link href="<?= $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet">
<link href='<?= $this->baseUrl();?>/fullcalendar/fullcalendar.css' rel='stylesheet' />
<link href='<?= $this->baseUrl();?>/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
<script src='<?= $this->baseUrl();?>/lib/jquery.min.js'></script>
<script src='<?= $this->baseUrl();?>/lib/jquery-ui.custom.min.js'></script>
<script src='<?= $this->baseUrl();?>/fullcalendar/fullcalendar.min.js'></script>
<title>Nubia Project</title>
<div class="header">
    <div class="logo">
        <a href="<?= $this->baseUrl() ?>" class="logo_link">N u b i a  Project</a>
    </div>
    <div class="info-panel">
        <div class="mainmenu">
            <?php 
                if($userType == "Guest") {
                    ?>
                        <a href="<?= $baseUrl ?>" class="logo_link">Home</a> |
                        <a href="<?= $baseUrl ?>/user/signin" class="logo_link">Login</a> |
                        <a href="<?= $baseUrl ?>" class="logo_link">About Nubia</a> |
                        <a href="<?= $baseUrl ?>/index/about" class="logo_link">About Team</a>
                    <?php
                }
                else {
                    ?>
                       <a href="<?= $baseUrl ?>" class="logo_link">Home</a> |
                       <a href="<?= $baseUrl ?>" class="logo_link">Profile</a> |
                       <a href="<?= $baseUrl ?>/user/signout" class="logo_link">Logout</a> 
                    <?php
                }
            ?>
        </div>
        <div class="welcome">
            <div class="welcome_text">
               Welcome : <?= $userType ?>
            </div>
        </div>
    </div>
</div>
<?php 
    if($userType != "Guest") {
        ?>
        <div class="menu">
            <div class="urgent">
                Main Menu 
            </div>
            <center>
                <div class="main_links">
                    <?php if($userType == "admin") {?>
                    <a href="<?= $this->baseUrl() ?>/patient/add" class="main_link" style=""> Add Patient </a> |
                    <a href="<?= $this->baseUrl() ?>/patient/add" class="main_link"> Add User </a> |
                    <a href="<?= $this->baseUrl() ?>/patient/search" class="main_link"> Search Patients </a> |
                    <a href="<?= $this->baseUrl() ?>/visit/add" class="main_link"> Create visit </a>
                    <?php } else if ($userType == "clinician") { ?>
                    <a href="<?= $this->baseUrl() ?>/patient/add" class="main_link" style=""> Add Patient </a> |
                    <a href="<?= $this->baseUrl() ?>/patient/search" class="main_link"> Search Patients </a> |
                    <a href="<?= $this->baseUrl() ?>/visit/add" class="main_link"> Create visit </a>
                    <?php } else if ($userType == "physician") { ?>
                    <a href="" class="main_link" style=""> Main Link 1 </a> |
                    <a href="" class="main_link"> Main Link 2 </a> |
                    <a href="" class="main_link"> Main Link 3 </a> |
                    <a href="" class="main_link"> Main Link 4 </a>
                    <?php } ?>
                </div>
            </center>
        </div>
        <?php
    }
?>
<div class="content">
    <?php echo $this->layout()->content; ?>
</div>