<?php
    $baseUrl = $this->baseUrl();
        $userType = "Guest";
        $authorization = Zend_Auth::getInstance();
        if ($authorization->hasIdentity()) {
            $authInfo = $authorization->getIdentity();
            $userType = $authInfo['userType'];
        }
        
        $sess = new Zend_Session_Namespace('Nubia_ACL');
        $back = $sess->prePage;
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Nubia Project</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

	<!--link rel="stylesheet/less" href="less/bootstrap.less" type="text/css" /-->
	<!--link rel="stylesheet/less" href="less/responsive.less" type="text/css" /-->
	<!--script src="js/less-1.3.3.min.js"></script-->
	<!--append ‘#!watch’ to the browser URL, then refresh the page. -->
	
        <link href="<?= $this->baseUrl() ?>/css/bootstrap.min.css" rel="stylesheet">
        <link href="<?= $this->baseUrl() ?>/css/our-css.css" rel="stylesheet">
        <link href='<?= $this->baseUrl();?>/fullcalendar/fullcalendar.css' rel='stylesheet' />
        <link href='<?= $this->baseUrl();?>/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
        <link href="<?= $this->baseUrl();?>/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <script src='<?= $this->baseUrl();?>/lib/jquery.min.js'></script>
        <script src='<?= $this->baseUrl();?>/lib/jquery-ui.custom.min.js'></script>
        <script src='<?= $this->baseUrl();?>/fullcalendar/fullcalendar.min.js'></script>
        <style>
            .container {
                width: 100%;
                padding-left: 0px;
                padding-right: 0px;
            }
            
            .right_menu {
                width: 100%;
                height: 100%;
                margin: 0 auto;
                border-left-style: solid;
                border-left-width: 2px;
                border-left-color: cadetblue;
            }
            
            .table {
                background: white;
            }
            .nav-item:hover {
                background-color: #22475E;
            }
            
            .nav_item_link:hover {
                color: white !important;
            }
            
            .navbar-brand {
                padding: 0px;
            }
            
            .nav_row {
                margin-left: 0px;
                margin-right: 0px;
            }
            
            .nav_column {
                padding: 0px;
            }
        </style>
     
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/jquery-ui.min.css" type="text/css" /> 

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
  <![endif]-->

  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
  <link rel="shortcut icon" href="img/favicon.png">
  
</head>

<!--
<body style="background: url(<?php //echo $this->baseUrl() ?>/imgs/pw_maze_white.png)">
-->
<body style="background: url(<?= $this->baseUrl() ?>/imgs/cream_pixels.png)">
    
   
    
    
<div class="container">
    <div class="row clearfix nav_row" >
            <div class="col-md-12 column nav_column">
                <div class="navbar navbar-default">
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                        <a class="navbar-brand" href="<?= $this->baseUrl() ?>"><img src="<?= $this->baseUrl() ?>/imgs/sma3a.png" style="margin-right: 10PX;width: 42px;padding-top: 7px;margin-left: 36px;" width="25px">N u b i a   Project</a>
                    </div>
                    <div class="navbar-collapse collapse navbar-responsive-collapse">
              
                      
                      
                        <?php 
                            if($userType == "Guest") {
                                ?>
                                    <ul class="nav navbar-nav navbar-right">
                                        <li class='nav-item'><a href="<?= $baseUrl ?>" class="nav_item_link">Home</a></li>
                                        <li class='nav-item'><a href="<?= $baseUrl ?>/user/signin" class="nav_item_link">Login</a><li>
                                        <li class='nav-item'><a href="<?= $baseUrl ?>" class="nav_item_link">About Nubia</a><li>
                                        <li class='nav-item'><a href="<?= $baseUrl ?>/index/about" class="nav_item_link">About Team</a><li>
                                <?php
                            }
                            else {
                                ?>
                                    <form class="navbar-form navbar-left" method="get" action='<?= $this->baseUrl() ?>/patient/search'>
                                        <input type="text" name="key" id="key" class="form-control col-lg-8" placeholder="Search Patient" onfocus="this.style.width = '355px'" onblur="this.style.width= '180px'">
                                    </form>
                                    <ul class="nav navbar-nav navbar-right">
                                       <li class='nav-item'><a href="<?= $baseUrl ?>" class="nav_item_link">Home</a><li>
                                       <li class='nav-item'><a href="<?= $baseUrl."/user/show-Profile/userId/".$authInfo['userId'] ?>" class="nav_item_link">Profile</a><li>
                                       <li class='nav-item'><a href="<?= $baseUrl ?>/user/signout" class="nav_item_link">Logout</a><li>
                                <?php
                            }
                        ?>
                        
                        <li>
                            <a>
                              <div class="welcome">
                                <div class="welcome_text">
                                   Welcome : <img src="<?= $this->baseUrl(); ?>/imgs/<?= $userType ?>.png" style="margin-right: 4px" width="20"> <?= $userType ?>
                                </div>
                            </div>
                            </a>
                        </li>
                      </ul>
                    </div>
                  </div>
            </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-1 column"></div>
            <div class="col-md-11 column"> 
                <?php echo $this->layout()->content; ?>           
            </div>
    </div>

<?php if($userType == "admin") { ?>
    <div class="right_content" id="right_content">
        <table cellspacing='0' class="table table-striped table-hover right_menu">
            <tr><th><img src="<?= $this->baseUrl(); ?>/imgs/adminDashBoard.png" width="20px" style="margin-right: 4px"> Admin Dashboard</th></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/user/notification"><img src="<?= $this->baseUrl(); ?>/imgs/notification.png" width="20px" style="margin-right: 4px"><div id="noti" class="noti"></div> Notifications</a></td></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/patient/add"><img src="<?= $this->baseUrl(); ?>/imgs/add.png" width="16px" style="margin-right: 4px"> Add Patient</td></a></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/patient/search" style="text-decoration: none"><img src="<?= $this->baseUrl(); ?>/imgs/search.png" style="margin-right: 4px">Search Patients</td></a></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/user/add"><img src="<?= $this->baseUrl(); ?>/imgs/addUser.png" width="16px" style="margin-right: 4px">Add Users</a></td></tr>

            <tr><th><img src="<?= $this->baseUrl(); ?>/imgs/urgentLink.png" width="20px" style="margin-right: 4px">Urgent Links</th></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/visit/add"><img src="<?= $this->baseUrl(); ?>/imgs/createVisit.png" style="margin-right: 4px">Create Visit</a></td></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/patient/update-history"><img src="<?= $this->baseUrl(); ?>/imgs/addPatientHistory.png" style="margin-right: 4px"> Add Patient History</a></td></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/"><img src="<?= $this->baseUrl(); ?>/imgs/result.png" width="20px" style="margin-right: 4px">Add Patient Result</a></td></tr>

            <tr><th><img src="<?= $this->baseUrl(); ?>/imgs/permission.png" style="margin-right: 4px">Permissions</th></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/permissions"><img src="<?= $this->baseUrl(); ?>/imgs/viewPermission.png" width="20px" style="margin-right: 4px"> View Permissions</a></td></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/permissions/edit"><img src="<?= $this->baseUrl(); ?>/imgs/editPermission.png" width="20px" style="margin-right: 4px"> Change Permissions</a></td></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/permissions/generateresources">Generate Resources</a></td></tr>
        </table>
    </div>
<button type="button" id="collapse-button" style="position: fixed;top: 363px;right: 172px;" class="btn btn-default" onclick="rightContentControl(this)">>></button>
<?php } else if ($userType == "clinician") { ?>
    <div class="right_content" id="right_content">
        <table cellspacing='0' class="table table-striped table-hover right_menu">
            <tr>
                <th>
                    Time : <div id='time' style="font-size: 30px"></div>
                    Date : <div id='date' style="font-size: 20px"></div> 
                    <div id='day' style="font-size: 15px"></div>
                </th>
            </tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/user/notification"><img src="<?= $this->baseUrl(); ?>/imgs/notification.png" width="20px" style="margin-right: 4px"><div id="noti" class="noti"></div> Notifications</a></td></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/patient/add"><img src="<?= $this->baseUrl(); ?>/imgs/add.png" width="16px" style="margin-right: 4px"> Add Patient</td></a></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/patient/add"> <img src="<?= $this->baseUrl(); ?>/imgs/result.png" width="20px" style="margin-right: 4px">Add Patient Result</a></th></tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/visit/add"><img src="<?= $this->baseUrl(); ?>/imgs/createVisit.png" style="margin-right: 4px">Create Visit</a></td></tr>
            <tr><th><img src="<?= $this->baseUrl(); ?>/imgs/activeVisit.png" width="20px" style="margin-right: 4px">Active Visit</th></tr>
            <tr><td>Visit 1</td></tr>
            <tr><th><img src="<?= $this->baseUrl(); ?>/imgs/today.png" width="16px" style="margin-right: 4px">Today's Visits</th></tr>
            <!--code for visit today list-->
            <?php
            if($this->visitToday)
            {
                foreach($this->visitToday as $visit)
                    echo "<tr><td><a href='".$this->baseUrl()."/visit/view/id/".$visit["id"]."'>".$visit["patname"].", ".$visit["created_date"]."</a></td></tr>";
            }
            ?>
            <!--end code-->
            <tr><th><a href="<?= $this->baseUrl() ?>/visit/list"><img src="<?= $this->baseUrl(); ?>/imgs/calender.png" style="margin-right: 4px" width="20"> Full Calender Visits</a></th></tr>
        </table>
    </div>
<button type="button" id="collapse-button" style="position: fixed;top: 363px;right: 172px;" class="btn btn-default" onclick="rightContentControl(this)">>></button>
    <?php } else if($userType == "physician") { ?>
    <div class="right_content" id="right_content">
        <table cellspacing='0' class="table table-striped table-hover right_menu">
            <tr>
                <th>
                    Time : <div id='time' style="font-size: 30px"></div>
                    Date : <div id='date' style="font-size: 20px"></div> 
                    <div id='day' style="font-size: 15px"></div>
                </th>
            </tr>
            <tr><td><a href="<?= $this->baseUrl(); ?>/user/notification"><img src="<?= $this->baseUrl(); ?>/imgs/notification.png" width="20px" style="margin-right: 4px"><div id="noti" class="noti"></div> Notifications</a></td></tr>
            <tr><td><a href="<?= $this->baseUrl()."/user/show-Profile/editProfile/1/userId/".$authInfo['userId']; ?>"><img src="<?= $this->baseUrl(); ?>/imgs/editProfile.png" width="20px" style="margin-right: 4px">Edit Profile</td></a></tr>
            <tr><th><img src="<?= $this->baseUrl(); ?>/imgs/activeVisit.png" width="20px" style="margin-right: 4px">Active Visit</th></tr>
            <tr><td>Visit 1</td></tr>
            <tr><th><img src="<?= $this->baseUrl(); ?>/imgs/today.png" width="16px" style="margin-right: 4px"> Today's Visits</th></tr>
            <!--code for visit today list-->
            <?php
            if($this->visitToday)
            {
                foreach($this->visitToday as $visit)
                    echo "<tr><td><a href='".$this->baseUrl()."/visit/view/id/".$visit["id"]."'>".$visit["patname"].", ".$visit["created_date"]."</a></td></tr>";
            }
            ?>
            <!--end code-->
            <tr><th>Accepted Visits</th></tr>
            <tr><th><a href="<?= $this->baseUrl() ?>/visit/list"><img src="<?= $this->baseUrl(); ?>/imgs/calender.png" style="margin-right: 4px" width="20"> Full Calender Visits</a></th></tr>
        </table>
    </div>
    <button type="button" id="collapse-button" style="position: fixed;top: 363px;right: 172px;" class="btn btn-default" onclick="rightContentControl(this)">>></button>
<?php } ?>
</div>
</body>
</html>
<script>
    <?php if ($userType == "physician" || $userType == "clinician") { ?>
    window.onload = CreateTime(document.getElementById("date"),document.getElementById("time"), document.getElementById("day"));
    
    <?php } 
        if($userType != "guest") {
            ?>
                window.onload = setInterval(function(){
                                    loadNotifications();
                                },2000);       
            <?php
        }     
    ?>
        
    rightContentAppear = true;
    userId = 1;
    function rightContentControl(input) {
        if(rightContentAppear) {
            document.getElementById('right_content').style.right = '-200px';
            input.value = '<<';
            input.style.right = '0px';
            rightContentAppear = false;
        }
        else {
            document.getElementById('right_content').style.right = '-3px';
            input.value = '>>';
            input.style.right = '172px'; 
            rightContentAppear = true;
        }  
    }

    function CreateTime(dateElement, timeElement, dayElement) {
        var weekday = new Array(7);
        weekday[0]=  "Sunday";
        weekday[1] = "Monday";
        weekday[2] = "Tuesday";
        weekday[3] = "Wednesday";
        weekday[4] = "Thursday";
        weekday[5] = "Friday";
        weekday[6] = "Saturday";
        window.setInterval(function() {
            var currentdate = new Date(); 
            var day = currentdate.getDay();
            var date = currentdate.getDate() + "/" + (currentdate.getMonth()+1)  + "/" + currentdate.getFullYear();                 
            var time = currentdate.getHours() + ":" + currentdate.getMinutes() + ":" + currentdate.getSeconds();
            dateElement.innerHTML = date;
            timeElement.innerHTML = time;
            dayElement.innerHTML = weekday[day];
        }, 1000);
    }
    
    function loadNotifications() {
        var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {
            if(xhr.readyState === 4) {
                if(this.responseText !== 'noNew') {
                    notificationDiv = document.getElementById("noti");
                    notificationDiv.style.display = 'inline-block';  
                    notificationDiv.innerHTML = this.responseText;
                }
            }
        };
        userType = '<?= $userType ?>';
        if(userType != "admin") {
            userType = '-<?=    ucfirst($userType) ?>';
        }   
        xhr.open("get","<?=$this->baseUrl()?>/Ajax/get"+userType+"-Notification-Num");
        xhr.send();
    }
    
    $(function() {
	$("#key").autocomplete({
		source: "<?= $this->baseUrl() ?>/Autocomplete/get-patient",
		minLength: 1
	});	
        
    });

</script>



