<form method='POST'>
    <center>
        <input type='submit' value='Save' class='greyButton'>
        <a href='<?=$this->baseUrl()?>/permissions' class='greyButton'>Cancel</a>
    </center>
    <?php $fullRoles = $this->fullRoles; ?>

    <div style="display: inline-block;">
        <table cellspacing='0'>
            <tr><th>Action Name</th><th>Physician</th><th>Clinician</th><th>Guest</th><th>Admin</th></tr>
            <?php
            $controllersNumber = count($fullRoles);
            $count = 0;

            foreach ($fullRoles as $key => $fullRole) {
                if($count == (int)($controllersNumber/2)+3) { ?>
                    </table>
                    </div>
                    <div style="display: inline-block;position: absolute;">
                    <table cellspacing='0'>
                    <tr><th>Action Name</th><th>Physician</th><th>Clinician</th><th>Guest</th><th>Admin</th></tr> 
                <?php } ?>
                <tr>
                    <th colspan = "5" style="text-align: center;font-size: 16px"><?= $key ?></th>
                </tr>
                <?php

                foreach ($fullRole as $action) {
                    $resourceId = $action['id'];
                    $actionName = $action['action'];
                    $roles = $action['roles'];
                    echo "<tr>";
                    echo "<th>$actionName</th>";
                    foreach ($roles as $roleKey=>$role) {
                        $checked = $role['status']?"checked":"";
                        echo "<td><input type='checkbox' name='$roleKey::$resourceId' value='$roleKey::$resourceId' $checked></td>";   
                    }
                    echo "</tr>";     
                } 
                $count++;
            }
            ?>
        </table>
    </div>
</form>

           
	
