<form method='POST'>
<div class="row clearfix">
    <div class="col-md-4 column"></div>
    <div class="col-md-4 column">

        <input type='submit' value='Save' class="btn btn-primary">
        <a href='<?=$this->baseUrl()?>/permissions' class="btn btn-warning">Cancel</a>
   </div>
    <div class="col-md-4 column"></div>
</div>
<br><br>
<?php $fullRoles = $this->fullRoles; ?>

<div class="row clearfix">
    <div class="col-md-1 column"></div>
    <div class="col-md-5 column">
    <table cellspacing='0' class="table table-striped table-hover">
	<tr>
                <th>Action Name</th>
            <?php 
                foreach ($this->roles as $role) {
                    echo "<th>".$role['name']."</th>";
                }
            ?>
            </tr>
        <?php
        $controllersNumber = count($fullRoles);
        $count = 0;

        foreach ($fullRoles as $key => $fullRole) {
            if($count == (int)($controllersNumber/2)+3) { ?>
                </table>
                </div>
                <div class="col-md-5 column">
                <table cellspacing='0' class="table table-striped table-hover">
                <tr>
                    <th>Action Name</th>
                    <?php 
                        foreach ($this->roles as $role) {
                            echo "<th>".$role['name']."</th>";
                        }
                    ?>
                </tr> 
            <?php } ?>
            <tr>
                <th colspan = "5" style="text-align: center;font-size: 16px"><?= $key ?></th>
            </tr>
            <?php

                foreach ($fullRole as $action) {
                    $resourceId = $action['id'];
                    $actionName = $action['action'];
                    $roles = $action['roles'];
                    echo "<tr>";
                    echo "<th>$actionName</th>";
                    foreach ($roles as $roleKey=>$role) {
                        $checked = $role['status']?"checked":"";
                        echo "<td><input type='checkbox' name='$roleKey::$resourceId' value='$roleKey::$resourceId' $checked></td>";   
                    }
                    echo "</tr>";     
                } 
                $count++;
            }
            ?>
                </table>
</div>
    <div class="col-md-1 column"></div>
</div>
</form>

           
	
