<link href="<?= $this->baseUrl() ?>/css/tableStyle.css" rel="stylesheet">
<?php
echo "<form method='POST'>";
echo "<center><input type='submit' value='Save' class='greyButton'>";
echo "<a href='".$this->baseUrl()."/permissions' class='greyButton'>Cancel</a></center>";
$fullRoles = $this->fullRoles;

?>

          <div style="display: inline-block;">
        <table cellspacing='0'>
	<tr><th>Action Name</th><th>Physician</th><th>Clinician</th><th>Guest</th><th>Admin</th></tr>
    <?php
    $controllersNumber = count($fullRoles);
    $count = 0;

foreach ($fullRoles as $key => $fullRole) {
    ?>  
        <?php if($count == (int)($controllersNumber/2)+3) { ?>
        </table>
          </div>
        <div style="display: inline-block;position: absolute;">
        <table cellspacing='0'>
	<tr><th>Action Name</th><th>Physician</th><th>Clinician</th><th>Guest</th><th>Admin</th></tr> 
        <?php } ?>
        <tr>
            <th colspan = "5" style="text-align: center;font-size: 16px"><?= $key ?></th>
        </tr>
        <?php
    $fullResources = $fullRole['resources'];
    
    foreach ($fullRole as $action) {
        $resourceId = $action['id'];
        $actionName = $action['action'];
        $roles = $action['roles'];
        echo "<tr>";
        echo "<th>".$actionName."</th>";
        foreach ($roles as $role) {
            
                $checked = $role['status']?"checked":"";
                echo "<td><input type='checkbox' name='".$role['id']."::".$resourceId."' value='".$role['id']."::".$resourceId."' ".$checked."></td>";   
        }
        echo "</tr>";     
    } 
    $count++;
}
echo "</table>";
echo "</div>";
echo "</form>";
?>

           
	
