<br />
<div id="view-content">
    <h1>Vital-Results :</h1>
    <h2>Vital-Results Statistics</h2>
    <ul>
        <li>
            <b>Number of Vital-Results : <?= $this->vitalResultsStatistics['count'] ?></b>
        </li>
        <li>
            <b>Last Inserted Vital-Result : --------</b>
        </li>
        <li>
            <b>Last Updated Vital-Result : --------</b>
        </li>
    </ul>
  
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/Vitalresult/add">Add Vital-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Vitalresult/view">View Vital-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Vitalresult/delete">Delete Vital-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Vitalresult/edit">Edit Vital-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Vitalresult/search">Search Vital-Result</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Vitalresult/list">List Vital-Results</a></li>
        
    </ul>
</div>