<div class="row clearfix">
    <div class="col-md-8 column">
        <span class="label label-success" style="font-size: 20px">Vitalresults</span>
        <span class="label label-success" style="font-size: 15px">Vitalresults Statistics</span>
        <ul class="list-group">
            <li class="list-group-item">
              <span class="badge"><?= $this->vitalResultsStatistics['count'] ?></span>
              Number of Vitalresults :
            </li>
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Joined Vitalresult :
            </li>
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Joined Vitalresult :
            </li>
          </ul>

        <div class="btn-group btn-group-justified">
            <a href="<?= $this->baseUrl() ?>/Vitalresult/add" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/add.png" style="width: 15px;margin-right: 5px">Add Vitalresult</a>
        <a href="<?= $this->baseUrl() ?>/Vitalresult/search" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/search.png" style="width: 15px;margin-right: 5px">Search Vitalresults</a>
        <a href="<?= $this->baseUrl() ?>/Vitalresult/list" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/list.png" style="width: 15px;margin-right: 5px">List Vitalresults</a>
        </div>
        <br><br>
        <a href="javascript:history.back();" class="btn btn-default">Back</a>    
    </div>
    <div class="col-md-2 column"></div>
</div>
