<br /><br />
<div id="view-content">
    <h1>Vital-result View : </h1>
    <?php
        if($this->vitalResult) {
            ?>
            <b>Visit Request : </b><?= $this->vitalResult[0]['visit_request_id'] ?><br />
            <b>Vital : </b><?= $this->vitalResult[0]['vitalName'] ?><br />
            <?php
                if($this->vitalResult[0]['vital_data']) {
                    ?><b>Vital Data: </b><?= $this->vitalResult[0]['vital_data'] ?><br /><?php
                }
                else {
                    ?><b>Vital Data: </b>Pending<br /><?php
                }
            ?>
            <a href="<?= $this->baseUrl() ?>/Vitalresult/edit?radId=<?= $this->vitalResult[0]['vital_id'] ?>&reqId=<?= $this->vitalResult[0]['visit_request_id'] ?>">Edit </a>
            <a href="<?= $this->baseUrl() ?>/Vitalresult/delete?radId=<?= $this->vitalResult[0]['vital_id'] ?>&reqId=<?= $this->vitalResult[0]['visit_request_id'] ?>">Delete </a>
            <?php
        }
        else {
            ?><h2>Not Found !!</h2><?php
        }
    ?>
    <a href="javascript:history.back();">Back</a>         
</div>