
<div class="row clearfix">
    <span class="label label-primary" style="font-size: 25px">Add Patient</span>
    <br><br><br>
    <form class="form-horizontal" method="post" action="<?php echo $this->baseUrl().$this->action; ?>">
  <fieldset>
    <legend>Basic Info</legend>
    <div class="form-group">
      <div class="col-lg-5">
        <input type="hidden" name="patientId" value="<?php if(isset($this->patientId)){echo $this->patientId;}?>"><br>
        <?= $this->form->name?>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->sex?>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->IDNumber?>
      </div>
    </div> 
    
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->DOB?>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->martial_status?>
      </div>
    </div>  
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->job?>
      </div>
    </div>  
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->ins_no?>
      </div>
    </div>   
  </fieldset>
   <br>     
    <fieldset>
        <legend>Contact Info</legend>
        <div class="form-group">
          <div class="col-lg-5">
            <?= $this->form->city?>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-5">
            <?= $this->form->region?>
          </div>
        </div>  
        <div class="form-group">
          <div class="col-lg-5">
            <?= $this->form->street?>
          </div>
        </div>          
        <div class="form-group">
          <div class="col-lg-5">
            <?= $this->form->telephone?>
          </div>
        </div> 
        <div class="form-group">
          <div class="col-lg-5">
            <?= $this->form->mobile?>
          </div>
        </div>  
        <div class="form-group">
          <div class="col-lg-5">
            <?= $this->form->postal?>
          </div>
        </div>        
        <div class="form-group">
           <div class="col-lg-5 col-lg-offset-0">
               <?= $this->form->btn?>
           </div>
         </div>
  </fieldset>
</form>
    
    
  
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
</div>
