<br /><br />
<div id="view-content">
    <h1>Patients :</h1>
    <h2>Patients Statistics : </h2>
    <ul>
        <li>
            <b>Number of Patients : </b>
        </li>
        <li>
            <b>Last Joined Patient : --------</b>
        </li>
    </ul>
  
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/Patient/add">Add Patient</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Patient/search">Delete Patient</a></li><!--lsaaaaaaaaaaaaa-->
        <li><a href="<?= $this->baseUrl() ?>/Patient/search">Edit Patient</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Patient/search">Search Patient</a></li>
        <li><a href="<?= $this->baseUrl() ?>/Patient/list">List Patients</a></li>
        
    </ul>
</div>