
    <!-- ///////////////////////////  -->
    <label><strong>Medications History :</strong></label><br> 
    <table style= 'border:1px solid black;'>
        <tr>
            <th>Medication</th>
            <th>Prescribed By</th>
            <th>Visit Date</th>
            <th>Action</th>
        </tr>
        <?php 
    for($i = 0; $i < count($this->medicationData); $i++){
        echo "<tr><td>".$this->medicationData[$i]["medication"]."</td>";
        echo "<td>".$this->medicationData[$i]["physician"]."</td>";
	echo "<td>".$this->medicationData[$i]["date"]."</td>";
        echo "<td><a href='".$this->baseUrl()."/medication-history/edit/id/".$this->medicationData[$i]["medHisID"]."/patientId/".$this->patientId."'>Edit  |</a><a href='".$this->baseUrl()."/medication-history/delete/id/".$this->medicationData[$i]["medHisID"]."/patientId/".$this->patientId."'>  Delete</a></td>";
        echo "</tr>";              
    }

?>
    </table>
    <!-- ///////////////////////////  -->
    <br><br>
    <label><strong>Diseases History :</strong></label><br> 
    <table style= 'border:1px solid black;'>
        <tr>
            <th>Disease</th>
            <th>Infection Time</th>
            <th>Action</th>
        </tr>
        <?php 
    for($i = 0; $i < count($this->diseaseData); $i++){
        echo "<tr><td style=' border:1px solid black;'>".$this->diseaseData[$i]["disease"]."</td>";
	echo "<td>".$this->diseaseData[$i]["date"]."</td>";
        echo "<td><a href='".$this->baseUrl()."/disease-history/edit/id/".$this->diseaseData[$i]["disHisID"]."/patientId/".$this->patientId."'>Edit  |</a><a href='".$this->baseUrl()."/disease-history/delete/id/".$this->diseaseData[$i]["disHisID"]."/patientId/".$this->patientId."'>  Delete</a></td>";
        echo "</tr>";              
    }

?>
    </table>
    
    <!-- ///////////////////////////  -->
    <br><br>
    <label><strong>Surgeries History :</strong></label><br> 
    <table style= 'border:1px solid black;'>
        <tr>
            <th>Surgery Name</th>
            <th>Operated By</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
        <?php 
    for($i = 0; $i < count($this->surgeryData); $i++){
        echo "<tr><td style=' border:1px solid black;'>".$this->surgeryData[$i]["surgery"]."</td>";
        echo "<td style=' border:1px solid black;'>".$this->surgeryData[$i]["physician"]."</td>";
        echo "<td>".$this->surgeryData[$i]["date"]."</td>";
        echo "<td><a href='".$this->baseUrl()."/surgery-history/edit/id/".$this->surgeryData[$i]["sugHisID"]."/patientId/".$this->patientId."'>Edit  |</a><a href=''".$this->baseUrl()."/surgery-history/delete/id/".$this->surgeryData[$i]["sugHisID"]."/patientId/".$this->patientId."'>  Delete</a></td>";
        echo "</tr>";              
    }

?>
    </table>
    
    <br><br>
    <a href="<?php echo $this->baseUrl()."/patient/showprofile/patientId/".$this->patientId; ?>">Back</a>    

