     <!-- ///////////////////////////  -->
<div class="row clearfix">
    <div class="col-md-10 column" style="margin-top: 30px;">
        <span class="label label-primary" style="font-size: 25px">Previous Visits</span>
        <br><br>
<table class='table table-striped table-hover'>
        <tr>
            <th>Medical Group</th>
            <th>Physician Name</th>
            <th>Description</th>
            <th>Visit Date</th>
            <th>Type</th>
            <th>Notes</th>
            <th>Dependency</th>
            <th>GP</th>
        </tr>
        <?php 
    if($this->previousVisits){
        for($i = 0; $i < count($this->previousVisits); $i++){
            echo "<tr><td>".$this->previousVisits[$i]["group_name"]."</td>";
            echo "<td>".$this->previousVisits[$i]["physician"]."</td>";
            echo "<td>".$this->previousVisits[$i]["description"]."</td>";
            echo "<td>".$this->previousVisits[$i]["date"]."</td>";
            echo "<td>".$this->previousVisits[$i]["type"]."</td>";
            echo "<td>".$this->previousVisits[$i]["notes"]."</td>";
            echo "<td>".$this->previousVisits[$i]["depandency"]."</td>";
            echo "<td>".$this->previousVisits[$i]["gp_id"]."</td>";
            echo "</tr>";              
        }
    }

?>
    </table>
    </div>
    <br><br>
    <div class="col-md-10 column" style="margin-top: 100px;">
        <span class="label label-primary" style="font-size: 25px">Accepted Visits</span>
        <br><br>
        <table class='table table-striped table-hover'>
        <tr>
            <th>Medical Group</th>
            <th>Physician Name</th>
            <th>Description</th>
            <th>Visit Date</th>
            <th>Type</th>
            <th>Notes</th>
            <th>Dependency</th>
            <th>GP</th>
        </tr>
        <?php 
        if($this->acceptedVisits){
            for($i = 0; $i < count($this->acceptedVisits); $i++){
                echo "<tr><td>".$this->acceptedVisits[$i]["group_name"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["physician"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["description"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["date"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["type"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["notes"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["depandency"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["gp_id"]."</td>";
                echo "</tr>";              
            }
        }

?>
    </table>
    </div>
            <!-- ///////////////////////////  -->
    <div class="col-md-10 column" style="margin-top: 100px;">
        <span class="label label-primary" style="font-size: 25px">Pending Visits</span>
        <br><br>
        <table class='table table-striped table-hover'>
        <tr>
            <th>Medical Group</th>
            <th>Description</th>
            <th>Visit Date</th>
            <th>Type</th>
            <th>Notes</th>
            <th>Dependency</th>
            <th>GP</th>
        </tr>
        <?php 
        if($this->pendingVisits){
            for($i = 0; $i < count($this->pendingVisits); $i++){
                echo "<tr><td>".$this->pendingVisits[$i]["group_name"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["description"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["date"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["type"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["notes"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["depandency"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["gp_id"]."</td>";
                echo "</tr>";              
            }
        }

?>
    </table>
    <br><br>

    <a href="javascript:history.back();">Back</a>    
    </div>
    </div>