
        <!-- ///////////////////////////  -->
    <label><strong>Pending Visits :</strong></label><br> 
    <table>
        <tr>
            <th>Medical Group</th>
            <th>Description</th>
            <th>Visit Date</th>
            <th>Type</th>
            <th>Notes</th>
            <th>Dependency</th>
            <th>GP</th>
        </tr>
        <?php 
    for($i = 0; $i < count($this->pendingVisits); $i++){
        echo "<tr><td style=' border:1px solid black;'>".$this->pendingVisits[$i]["group_name"]."</td>";
        echo "<td>".$this->pendingVisits[$i]["description"]."</td>";
	echo "<td>".$this->pendingVisits[$i]["date"]."</td>";
        echo "<td>".$this->pendingVisits[$i]["type"]."</td>";
        echo "<td>".$this->pendingVisits[$i]["notes"]."</td>";
        echo "<td>".$this->pendingVisits[$i]["depandency"]."</td>";
        echo "<td>".$this->pendingVisits[$i]["gp_id"]."</td>";
        echo "</tr>";              
    }

?>
    </table>
    <br><br>
    <a href="<?php echo $this->baseUrl()."/patient/showprofile/patientId/".$this->patientId; ?>">Back</a>    
