     <!-- ///////////////////////////  -->
    <label><strong>Previous Visits :</strong></label><br> 
    <table style= 'border:1px solid black;'>
        <tr>
            <th>Medical Group</th>
            <th>Physician Name</th>
            <th>Description</th>
            <th>Visit Date</th>
            <th>Type</th>
            <th>Notes</th>
            <th>Dependency</th>
            <th>GP</th>
        </tr>
        <?php 
    for($i = 0; $i < count($this->previousVisits); $i++){
        echo "<tr><td>".$this->previousVisits[$i]["group_name"]."</td>";
        echo "<td>".$this->previousVisits[$i]["physician"]."</td>";
        echo "<td>".$this->previousVisits[$i]["description"]."</td>";
	echo "<td>".$this->previousVisits[$i]["date"]."</td>";
        echo "<td>".$this->previousVisits[$i]["type"]."</td>";
        echo "<td>".$this->previousVisits[$i]["notes"]."</td>";
        echo "<td>".$this->previousVisits[$i]["depandency"]."</td>";
        echo "<td>".$this->previousVisits[$i]["gp_id"]."</td>";
        echo "</tr>";              
    }

?>
    </table>
    <br><br>
    <a href="<?php echo $this->baseUrl()."/patient/showprofile/patientId/".$this->patientId; ?>">Back</a>    
