<div class="row clearfix">
    <div class="col-md-10 column">
        <span class="label label-primary" style="font-size: 25px">Patients List</span>
        <br><br>
<table class='table table-striped table-hover'>
        <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Date of Birth</th>            
            <th>ID Number</th>
            <th>City</th>
            <th>Insurance Number</th>
            <th>Action</th>

        </tr>

<?php 
    for($i = 0; $i < count($this->patients); $i++){

        echo "<tr><td>".$this->patients[$i]["name"]."</td>";
        echo "<td>";
        if ($this->patients[$i]["sex"] == 'F') {
            echo "Female";
        } elseif ($this->patients[$i]["sex"] == 'M') {
            echo "Male";
        } 
        echo "</td>";
        echo "<td>".$this->patients[$i]["DOB"]."</td>";        
	echo "<td>".$this->patients[$i]["IDNumber"]."</td>";
        echo "<td>".$this->patients[$i]["city"]."</td>";
        echo "<td>".$this->patients[$i]["ins_no"]."</td>";
        echo "<td><a href='".$this->baseUrl()."/patient/edit/patientId/".$this->patients[$i]['id']."' class='btn btn-default'>Edit</a>";
        echo "<a href='".$this->baseUrl()."/patient/delete/patientId/".$this->patients[$i]['id']."' class='btn btn-default'>Delete</a>";
        echo "<a href='".$this->baseUrl()."/patient/showprofile/patientId/".$this->patients[$i]['id']."' class='btn btn-info'> Patient Information </a></td>";
        echo "</tr>";       
    }

?>
    </table>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
</div>