<br /><br />
<div id="view-content">
        <!-- ///////////////////////////  -->
    <label><strong>Previous Visits :</strong></label><br> 
    <table style= 'border:1px solid black;'>
        <tr>
            <th style='border:1px solid black;'>Medical Group</th>
            <th style='border:1px solid black;'>Physician Name</th>
            <th style='border:1px solid black;'>Description</th>
            <th style='border:1px solid black;'>Visit Date</th>
            <th style='border:1px solid black;'>Type</th>
            <th style='border:1px solid black;'>Notes</th>
            <th style='border:1px solid black;'>Dependency</th>
            <th style='border:1px solid black;'>GP</th>
        </tr>
        <?php 
    for($i = 0; $i < count($this->previousVisits); $i++){
        echo "<tr><td style=' border:1px solid black;'>".$this->previousVisits[$i]["group_name"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->previousVisits[$i]["physician"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->previousVisits[$i]["description"]."</td>";
	echo "<td style='border:1px solid black;'>".$this->previousVisits[$i]["date"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->previousVisits[$i]["type"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->previousVisits[$i]["notes"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->previousVisits[$i]["depandency"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->previousVisits[$i]["gp_id"]."</td>";
        echo "</tr>";              
    }

?>
    </table>
    <br><br>
    <a href="javascript:history.back();">Back</a>    
</div>