<div class="row clearfix">
    <div class="col-md-10 column">
        <span class="label label-primary" style="font-size: 25px">Patients List</span>
        <br><br>
<table class='table table-striped table-hover'>
        <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Date of Birth</th>            
            <th>ID Number</th>
            <th>City</th>
            <th>Insurance Number</th>
            <th>Action</th>

        </tr>
<?php

if($this->patients)
{    
    $patient = $this->patients;
    foreach ($this->paginator as $patient)
    {
        echo "<tr><td>".$patient["name"]."</td>";
        echo "<td>";
        if ($patient["sex"] == 'F') {
            echo "Female";
        } elseif ($patient["sex"] == 'M') {
            echo "Male";
        } 
        echo "</td>";
        echo "<td>".$patient['DOB']."</td>";        
	echo "<td>".$patient['IDNumber']."</td>";
        echo "<td>".$patient['city']."</td>";
        echo "<td>".$patient['ins_no']."</td>";
        echo "<td><a href='".$this->baseUrl()."/patient/edit/patientId/".$patient['id']."' class='btn btn-default'>Edit</a>";
        echo "<a href='".$this->baseUrl()."/patient/delete/patientId/".$patient['id']."' class='btn btn-default'>Delete</a>";
        echo "<a href='".$this->baseUrl()."/patient/showprofile/patientId/".$patient['id']."' class='btn btn-info'> Patient Information </a></td>";        
        echo "</tr>";       
    }
    echo "</table>";
    echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
}
/*
for($i = 0; $i < count($this->patients); $i++){

echo "<tr><td>".$this->patients[$i]["name"]."</td>";
echo "<td>";
if ($this->patients[$i]["sex"] == 'F') {
   echo "Female";
} elseif ($this->patients[$i]["sex"] == 'M') {
   echo "Male";
} 
echo "</td>";
echo "<td>".$this->patients[$i]["IDNumber"]."</td>";
echo "<td>".$this->patients[$i]["region"]."</td>";
echo "<td>".$this->patients[$i]["city"]."</td>";
echo "<td>".$this->patients[$i]["street"]."</td>";
echo "<td>".$this->patients[$i]["postal"]."</td>";
echo "<td>".$this->patients[$i]["telephone"]."</td>";
echo "<td>".$this->patients[$i]["mobile"]."</td>";
echo "<td>".$this->patients[$i]["DOB"]."</td>";
echo "<td>".$this->patients[$i]["job"]."</td>";
echo "<td>".$this->patients[$i]["ins_no"]."</td>";
echo "<td><a href='edit/patientId/".$this->patients[$i]['id']."'>  Edit  |</a><a href='delete/patientId/".$this->patients[$i]['id']."'>  Delete</a></td>";
echo "</tr>";  

}
*/
?>
    </table>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
</div>

