<div class="row clearfix">
    <div class="col-md-10 column">
        <span class="label label-primary" style="font-size: 25px">Accepted Visits</span>
        <br><br>
<table class='table table-striped table-hover'>
        <tr>
            <th>Medical Group</th>
            <th>Physician Name</th>
            <th>Description</th>
            <th>Visit Date</th>
            <th>Type</th>
            <th>Notes</th>
            <th>Dependency</th>
            <th>GP</th>
        </tr>
        <?php 
    for($i = 0; $i < count($this->acceptedVisits); $i++){
        echo "<tr><td style=' border:1px solid black;'>".$this->acceptedVisits[$i]["group_name"]."</td>";
        echo "<td>".$this->acceptedVisits[$i]["physician"]."</td>";
        echo "<td>".$this->acceptedVisits[$i]["description"]."</td>";
	echo "<td>".$this->acceptedVisits[$i]["date"]."</td>";
        echo "<td>".$this->acceptedVisits[$i]["type"]."</td>";
        echo "<td>".$this->acceptedVisits[$i]["notes"]."</td>";
        echo "<td>".$this->acceptedVisits[$i]["depandency"]."</td>";
        echo "<td>".$this->acceptedVisits[$i]["gp_id"]."</td>";
        echo "</tr>";              
    }

?>
    </table>
    <br><br>
    <a href="javascript:history.back();">Back</a> 
    </div>
</div>

