<br /><br />
<div id="view-content">
    <form action="<?php echo $this->baseUrl()."/patient/search"; ?>" method="post">
        <?php           
        echo $this->form->IDNumber;
        echo $this->form->btn;
       ?>
    </form>
</div>

<div id="search">
    <form class="form-inline" role="form" method="post" action="">
        <label class="col-xs-push-1 control-label">Patient </label>
        <input type="text" style="width: 300px" id="name" name="name" class="form-control" placeholder="SEARCH BY NAME OR ID .. "/>
        <button type="submit" class="btn btn-primary">search</button>
    </form>
</div>

<?php
    if($this->patients)
    {
        echo "<table>";
        echo "<tr><th>Name</th>";
        echo "<th>ID Number</th>";
        echo "<th>sex";
        echo "<th>number</th></tr>";
        foreach ($this->patients as $patient) {
            echo "<tr>";
            echo "<td>".$patient["name"]."</td>";
            echo "<td>".$patient["IDNumber"]."</td>";
            echo "<td>".$patient["sex"]."</td>";
            echo "<td>".$patient["patient_num"]."</td>";
            echo "<td>";
            echo "<a href='". $this->baseUrl()."/visit/add?id=".$patient["id"]."'> New Visit </a> - ";
            echo "<a href='". $this->baseUrl()."/visit/view?patientid=".$patient["id"]."'> Visits Details </a> - ";
            echo "<a href='". $this->baseUrl()."/patient/showprofile/patientId/".$patient["id"]."'> Patient Information </a>";
            echo "</td>";
            echo "</tr>";
        }
        echo "</table>";
    }
    else
        echo "<h3>No Data</h3> -- <a href=".$this->baseUrl()."/patient/add>add patient</a>";
?>