<div class="row clearfix">
    <div class="col-md-10 column">
<?php if($this->fullData){?>

	<div class="row">
  		<div class="col-sm-10"><h1><?= $this->fullData["name"]; ?></h1></div>
    	<div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="<?= $this->baseUrl() ?>/imgs/profile.png"></a></div>
    </div>
    <div class="row">
  		<div class="col-sm-3"><!--left col-->
              
          <ul class="list-group">
            <li class="list-group-item text-muted">Profile</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Gender</strong></span> <?php if ($this->fullData["sex"] == 'F') {
                                                                        echo "Female";
                                                                    } elseif ($this->fullData["sex"] == 'M') {
                                                                        echo "Male";
                                                                    } ?></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>ID Number</strong></span> <?= $this->fullData["IDNumber"]; ?></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>GP's name</strong></span> <?= $this->fullData["gpname"]; ?></li>
            
          </ul> 
               
          <div class="panel panel-default">
            <div class="panel-heading">Contact <i class="fa fa-link fa-1x"></i></div>
            <div class="panel-body">
                <label>Region : </label><label><?= $this->fullData["region"]; ?></label><br>
                <label>City : </label><label><?= $this->fullData["city"]; ?></label><br>
                <label>Street : </label><label><?= $this->fullData["street"]; ?></label><br>
                <label>Postal Code : </label><label><?= $this->fullData["postal"]; ?></label><br>
                <label>Telephone : </label><label><?= $this->fullData["telephone"]; ?></label><br>
                <label>Mobile : </label><label><?= $this->fullData["mobile"]; ?></label>
            </div>
            
          </div>
             
          
                    
    <ul class="list-group">
        <li class="list-group-item text-muted">Information <i class="fa fa-dashboard fa-1x"></i></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Marital Status</strong></span> <?= $this->fullData["martial_status"]; ?> .</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Date of Birth</strong></span> <?= $this->fullData["DOB"]; ?> .</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Job</strong></span> <?= $this->fullData["job"]; ?> .</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Insurance Number</strong></span> <?= $this->fullData["ins_no"]; ?> .</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Join Date</strong></span> <?= $this->fullData["join_date"]; ?> .</li>
    </ul> 
                    
          
        </div><!--/col-3-->
    	<div class="col-sm-9">
          
          <ul class="nav nav-tabs" id="myTab">
            <li class="active"><a href="#home" data-toggle="tab">Previous Visits</a></li>
            <li><a href="#messages" data-toggle="tab">Pending Visits</a></li>
            <li><a href="#settings" data-toggle="tab">Accepted Visits</a></li>
            <li><a href="#settings" data-toggle="tab">Drugs</a></li>
            <li><a href="#settings" data-toggle="tab">Surgeries</a></li>
            <li><a href="#settings" data-toggle="tab">Diseases</a></li>
          </ul>
              
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="home">
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                        <th>Medical Group</th>
                        <th>Physician Name</th>
                        <th>Description</th>
                        <th>Visit Date</th>
                        <th>Type</th>
                        <th>Notes</th>
                        <th>Dependency</th>
                        <th>GP</th>
                    </tr>
                  </thead>
                  <tbody id="items">
                          <?php 
    if($this->previousVisits){
        for($i = 0; $i < count($this->previousVisits); $i++){
            echo "<tr><td>".$this->previousVisits[$i]["group_name"]."</td>";
            echo "<td>".$this->previousVisits[$i]["physician"]."</td>";
            echo "<td>".$this->previousVisits[$i]["description"]."</td>";
            echo "<td>".$this->previousVisits[$i]["date"]."</td>";
            echo "<td>".$this->previousVisits[$i]["type"]."</td>";
            echo "<td>".$this->previousVisits[$i]["notes"]."</td>";
            echo "<td>".$this->previousVisits[$i]["depandency"]."</td>";
            echo "<td>".$this->previousVisits[$i]["gp_id"]."</td>";
            echo "</tr>";              
        }
    }

?>
                  </tbody>
                </table>
              </div>
            </div>
            
              <!--  <hr>-->
                
            <div class="tab-pane fade" id="home" style='display: none'>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                        <th>Medical Group</th>
                        <th>Physician Name</th>
                        <th>Description</th>
                        <th>Visit Date</th>
                        <th>Type</th>
                        <th>Notes</th>
                        <th>Dependency</th>
                        <th>GP</th>
                    </tr>
                  </thead>
                  <tbody id="items">
        <?php 
        if($this->acceptedVisits){
            for($i = 0; $i < count($this->acceptedVisits); $i++){
                echo "<tr><td>".$this->acceptedVisits[$i]["group_name"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["physician"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["description"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["date"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["type"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["notes"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["depandency"]."</td>";
                echo "<td>".$this->acceptedVisits[$i]["gp_id"]."</td>";
                echo "</tr>";              
            }
        }

?>
                  </tbody>
                </table>
              </div>
            </div>
            <div class="tab-pane fade" id="home" style='display: none'>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                        <th>Medical Group</th>
                        <th>Description</th>
                        <th>Visit Date</th>
                        <th>Type</th>
                        <th>Notes</th>
                        <th>Dependency</th>
                        <th>GP</th>
                    </tr>
                  </thead>
                  <tbody id="items">
 <?php 
        if($this->pendingVisits){
            for($i = 0; $i < count($this->pendingVisits); $i++){
                echo "<tr><td>".$this->pendingVisits[$i]["group_name"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["description"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["date"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["type"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["notes"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["depandency"]."</td>";
                echo "<td>".$this->pendingVisits[$i]["gp_id"]."</td>";
                echo "</tr>";              
            }
        }

?>
                  </tbody>
                </table>
              </div>
            </div>              
               
 </div>
    <br>
    <a href="<?= $this->baseUrl()."/patient/showprofile/showPatientHistory/".$this->patientId; ?>" class='btn btn-info'>Patient Medical History</a><br> <!--Action to get all by join-->
    <br>    
    <a href="<?= $this->baseUrl()."/patient/showprofile/visits/".$this->patientId; ?>" class='btn btn-info'>Patient Visits</a><br><!--date < now-->


    <div class="btn-group btn-group-justified">
            <a href="<?= $this->baseUrl()."/Patient/add-History/patientId/".$this->patientId; ?>" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/add.png" style="width: 15px;margin-right: 5px">Add Medical History</a>
            <a href="<?= $this->baseUrl()."/patient/edit/patientId/".$this->patientId ?>" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/edit.png" style="width: 15px;margin-right: 5px">Edit Information</a>
            <a href="<?= $this->baseUrl() ?>/patient/delete/patientId/<?= $this->patientId ?>" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/deleteNoti.png" style="width: 15px;margin-right: 5px">Delete Patient</a>
        </div>
              </div><!--/table-resp-->
              
              
              
             </div><!--/tab-pane-->
            <!--/tab-pane-->
               
              </div><!--/tab-pane-->
          </div><!--/tab-content-->

        </div><!--/col-9-->
        
        <?php }else{
    echo "Error in retreiving data..";
}?>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
    <div class="col-md-2 column"></div>
</div>
    <script>
        $('#myTab a').click(function (e) {
                e.preventDefault();
                //$(this).s
       });

      
    </script>

