<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui.min.js"></script>
<link rel="stylesheet" href="<?= $this->baseUrl() ?>/css/jquery-ui.min.css" type="text/css" />
<div class="row clearfix">
    
        <div class="col-md-3 column">
            <div class="well bs-component">
            <h2>Medication History</h2>
            <form action="" method="post">
                Medication : <input type="text" id="medication" name="medication" placeholder="Type Medicaiton" />  
            </form>
            <input type="submit" value="Add" onclick="addMedicationHistory()" class="btn btn-default"/>
            <div id="medicationDiv" style="background-color: rgb(250, 250, 250);height: 153px;border-radius: 4px;border-style: solid;border-width: 1px;border-color: #DBDBDB;"></div>
            </div>
        </div>
        <div class="col-md-3 column">
            <div class="well bs-component">
            <h2>Disease History</h2>
            <form action="" method="post">
                Disease : <input type="text" id="disease" name="disease" placeholder="Type Disease"/>
            </form>
            <input type="submit" value="Add" onclick="addDiseaseHistory()" class="btn btn-default"/>
            <div id="diseaseDiv" style="background-color: rgb(250, 250, 250);height: 153px;border-radius: 4px;border-style: solid;border-width: 1px;border-color: #DBDBDB;"></div> 
            </div>
        </div>
        <div class="col-md-3 column">
            <div class="well bs-component">
            <h2>Surgery History</h2>
            <form action="" method="post">
                Surgery : <input type="text" id="surgery" name="surgery" placeholder="Type Surgery"/>
            </form>
            <input type="submit" value="Add" onclick="addSurgeryHistory()" class="btn btn-default"/>
            <div id="surgeryDiv" style="background-color: rgb(250, 250, 250);height: 153px;border-radius: 4px;border-style: solid;border-width: 1px;border-color: #DBDBDB;"></div>
            </div>
        </div>
    
</div>

<h3><a href="<?= $this->baseUrl() ?>/patient/showprofile/patientId/<?= $this->patientId ?>" class="btn btn-primary">Finish</a></h3>

<script type="text/javascript">
    patientId = <?= $this->patientId ?>;
$(function() {
	//autocomplete
	$("#medication").autocomplete({
		source: "<?= $this->baseUrl() ?>/Autocomplete/get-Medication",
		minLength: 1
	});	
        
        $("#disease").autocomplete({
		source: "<?= $this->baseUrl() ?>/Autocomplete/get-Disease",
		minLength: 1
	});
        
        $("#surgery").autocomplete({
		source: "<?= $this->baseUrl() ?>/Autocomplete/get-Surgery",
		minLength: 1
	});
        
});

function addMedicationHistory() {
    medication = document.getElementById('medication').value;
    var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {
            if(xhr.readyState === 4) {
                if(this.responseText === 'done') {
                    element = document.createElement("div");
                    element.innerHTML = medication;
                    document.getElementById('medication').value = "";
                    medDiv = document.getElementById('medicationDiv');
                    div = document.createElement("div");
                    div.innerHTML = medication;
                    div.setAttribute("class","label label-default");
                    div.style.display = "block";
                    div.style.fontSize = "15px";
                    medDiv.appendChild(div);
                }
                else {
                    $medDiv = document.getElementById('medicationDiv');
                    $medDiv.textContent = medication;
                    alert(this.responseText);
                }
            }
        };

        xhr.open("get","<?=$this->baseUrl()?>/Ajax/add-Medication-History?medication="+medication+"&patientId="+patientId);
        xhr.send();
}

function addDiseaseHistory() {
    disease = document.getElementById('disease').value;
    var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {
            if(xhr.readyState === 4) {
                if(this.responseText === 'done') {
                    element = document.createElement("div");
                    element.innerHTML = disease;
                    document.getElementById('disease').value = "";
                    disDiv = document.getElementById('diseaseDiv');
                    div = document.createElement("div");
                    div.innerHTML = disease;
                    div.setAttribute("class","label label-default");
                    div.style.display = "block";
                    div.style.fontSize = "15px";
                    disDiv.appendChild(div);
                }
                else {
                    $diseaseDiv = document.getElementById('diseaseDiv');
                    $diseaseDiv.textContent = disease;
                    alert(this.responseText);
                }
            }
        };

        xhr.open("get","<?=$this->baseUrl()?>/Ajax/add-Disease-History?disease="+disease+"&patientId="+patientId);
        xhr.send();
}

function addSurgeryHistory() {
    surgery = document.getElementById('surgery').value;
    var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {
            if(xhr.readyState === 4) {
                if(this.responseText === 'done') {
                    element = document.createElement("div");
                    element.innerHTML = surgery;
                    document.getElementById('surgery').value = "";
                    surDiv = document.getElementById('surgeryDiv');
                    div = document.createElement("div");
                    div.innerHTML = surgery;
                    div.setAttribute("class","label label-default");
                    div.style.display = "block";
                    div.style.fontSize = "15px";
                    surDiv.appendChild(div);
                }
                else {
                    $surgeryDiv = document.getElementById('surgeryDiv');
                    $surgeryDiv.textContent = surgery;
                    alert(this.responseText);
                }
            }
        };

        xhr.open("get","<?=$this->baseUrl()?>/Ajax/add-Surgery-History?surgery="+surgery+"&patientId="+patientId);
        xhr.send();
}
</script>
