<div id="view-content">

    <h1>Physician Groups :</h1>
    <h2>Physician Groups Statistics : </h2>
    <ul>
        <li>
            <b>Number of Physician Groups : </b>
        </li>
        <li>
            <b>Last Added Physician Groups : --------</b>
        </li>
    </ul>
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/physiciangroup/add">Add New Physician Group</a></li>
        <li><a href="<?= $this->baseUrl() ?>/physiciangroup/search/delete/1">Delete Physician Group</a></li>
        <li><a href="<?= $this->baseUrl() ?>/physiciangroup/search/edit/1">Edit Physician Group</a></li>
        <li><a href="<?= $this->baseUrl() ?>/physiciangroup/search">Search Physician Groups</a></li>
        <li><a href="<?= $this->baseUrl() ?>/physiciangroup/list">List Physician Groups</a></li>
        
    </ul>
</div>
