<div class="row clearfix">
    <div class="col-md-2 column"></div>
    <div class="col-md-6 column">
        <span class="label label-primary" style="font-size: 25px">Physician Group List</span>
        <br><br>
	<?php
            if ($this->physiciangroup) {
                echo "<table class='table table-striped table-hover'>";
                echo "<thead><tr><th>Name</th><th>Action</th></tr></thead>";
                foreach ($this->physiciangroup as $Physiciangroup) {
                    echo "<tr>";
                    echo "<td>".$Physiciangroup['name']."</td>";
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Physiciangroup/view/id/".$Physiciangroup['id']."' class='btn btn-info'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Physiciangroup/edit/id/".$Physiciangroup['id']."' class='btn btn-default'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Physiciangroup/delete/id/".$Physiciangroup['id']."' class='btn btn-default'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2> No, Physician Groups !!</h2>";
                echo "but you can <a href='".$this->baseUrl()."/physiciangroup/add' >Add Physiciangroup</a> ";
            }
        ?>
        <br>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
    <div class="col-md-2 column"></div>
</div>


