<div class="row clearfix">
    <div class="col-md-6 column">
<span class="label label-primary" style="font-size: 25px">Physician Group Search</span>
<br><br>
<form class="form-horizontal" method="GET">
    <fieldset>
        <legend>Search</legend>
        <div class="form-group">
          <div class="col-lg-10">            
          <label for="key" class="col-lg-2 control-label">Name</label>
              <input type="text" id="key" name="key" placeholder="Enter search key" class="form-control"/>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
              <input type="submit" value="Search" class="btn btn-primary"/>
          </div>
        </div>
    </fieldset>
</form>
    <?php
        if( $this->key ) {
            echo "<script>document.getElementById('key').value = '".$this->key."'; </script>";
            if ($this->physiciansgroup) {
                echo "<table class='table table-striped table-hover'>";
                echo "<tr><th>Name</th><th>Action</th></tr>";
                foreach ($this->physiciansgroup as $Physiciangroup) {
                    echo "<tr>";
                    echo "<td>".$Physiciangroup['name']."</td>";
                    echo "<td>";
                    echo "<a href='". $this->baseUrl()."/Physiciangroup/view?id=".$Physiciangroup['id']."'  class='btn btn-info'> View </a>";
                    echo "<a href='". $this->baseUrl()."/Physiciangroup/edit?id=".$Physiciangroup['id']."'  class='btn btn-default'> Edit </a>";
                    echo "<a href='". $this->baseUrl()."/Physiciangroup/delete?id=".$Physiciangroup['id']."'  class='btn btn-default'> Delete </a>";
                    echo "</td>";
                    echo "</tr>";
                }
                echo "</table>";
            }
            else {
                echo "<h2>Not Found !!</h2>";
            }
        }
        
    
    ?>
    </div>
    <div class="col-md-3 column"></div>
</div>

