<br /><br />
<div id="view-content">        
    <form method="post" action="<?php echo $this->baseUrl().$this->action ?>" >
        <input type="hidden" name="userId" value="<?php if(isset($this->userId)){echo $this->userId;}?>"><br>

            <?php
           echo $this->form->name."<br>";
           echo $this->form->sex."<br>";
           echo $this->form->email."<br>";
           echo $this->form->password."<br>";
           echo $this->form->telephone."<br>";
           echo $this->form->mobile."<br>";
           echo $this->form->role_id."<br>";
           echo "<div id='physBlock' style='display:none;'>".
           $this->physForm->title."<br>".
           $this->physForm->group_id."<br></div>";
           echo $this->form->btn;
            ?>
    </form>
        <a href="javascript:history.back();">Back</a>

</div>
<script>
function checkSelection() {
    
    var role = document.getElementsByName("role_id")[0].value;
        if(role == 2){
            document.getElementById("physBlock").style.display = 'block';
        }
}    
</script>