<div class="row clearfix">
    <span class="label label-primary" style="font-size: 25px">Edit User</span>
    <br><br><br>
    <form class="form-horizontal" method="post">
  <fieldset>
    <legend>Basic Info</legend>
    <div class="form-group">
      <div class="col-lg-5">
        <input type="hidden" name="userId" value="<?php if(isset($this->userId)){echo $this->userId;}?>"><br>
        <?= $this->form->name?>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->sex?>
      </div>
    </div>       
       <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->email?>
      </div>
    </div> 
    
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->password?>
      </div>
    </div>  

    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->form->role_id?>
      </div>
    </div>
    
    <div id='physBlock' style='display:none;'>
        <div class="form-group">
      <div class="col-lg-5">
        <?= $this->physForm->title?>
      </div>
    </div>
        
    <div class="form-group">
      <div class="col-lg-5">
        <?= $this->physForm->group_id?>
      </div>
    </div>        
    </div>
    
    
  </fieldset>
   <br>     
    <fieldset>
        <legend>Contact Info</legend>
        <div class="form-group">
          <div class="col-lg-5">
            <?= $this->form->telephone?>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-5">
            <?= $this->form->mobile?>
          </div>
        </div>      
        <div class="form-group">
           <div class="col-lg-5 col-lg-offset-0">
               <?= $this->form->btn?>
           </div>
         </div>
  </fieldset>
</form>
            <?php
          /* echo $this->form->name."<br>";
           echo $this->form->sex."<br>";
           echo $this->form->email."<br>";
           echo $this->form->password."<br>";
           echo $this->form->telephone."<br>";
           echo $this->form->mobile."<br>";
           echo $this->form->role_id."<br>";
           echo "<div id='physBlock' style='display:none;'>";
           echo $this->physForm->title."<br>";
           echo $this->physForm->group_id."<br>";
           echo "</div>"; 
           echo $this->form->btn;*/
            ?>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
</div>  

<script>
    var element = document.getElementsByName("role_id")[0];
    var role = element.options[element.selectedIndex].text;
    if(role == 'physician'){
        document.getElementById("physBlock").style.display = 'block';
    }

function checkSelection() {   
    var element = document.getElementsByName("role_id")[0];
    var role = element.options[element.selectedIndex].text;
    
        if(role == 'physician'){
            document.getElementById("physBlock").style.display = 'block';
        }
        else {
            document.getElementById("physBlock").style.display = 'none';
        }
}    
</script></div>