<div class="row clearfix">
    <span class="label label-primary" style="font-size: 25px">Add User</span>
    <br><br><br>
    <form class="form-horizontal" method="post" action="<?= $this->baseUrl()."/user/show-Profile" ?>">
  <fieldset>
    <legend>Basic Info</legend>
        <input type="hidden" name="userId" value="<?php if(isset($this->userId)){echo $this->userId;}?>"><br>
    <?php
if($this->physUser){
        echo "<input type='hidden' name='type' value='physician'/>";
        echo $this->form->name."<br>";
        echo $this->form->sex."<br>";
        echo $this->form->email."<br>";
        echo $this->form->password."<br>";
        echo $this->form->telephone."<br>";
        echo $this->form->mobile."<br>";
        echo $this->physForm->title."<br>";
        echo $this->physForm->group_id."<br>";
        echo $this->form->btn; 
}
if($this->adminClinUser){
        echo "<input type='hidden' name='type' value='adminOrClin'/>";
        echo $this->form->name."<br>";
        echo $this->form->sex."<br>";
        echo $this->form->email."<br>";
        echo $this->form->password."<br>";
        echo $this->form->telephone."<br>";
        echo $this->form->mobile."<br>";
        echo $this->form->btn;     
}
    ?>
    </form>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
</div>
