<br /><br />
<div id="view-content">
    <h1>Users :</h1>
    <h2>Users Statistics : </h2>
    <ul>
        <li>
            <b>Number of Users : </b>
        </li>
        <li>
            <b>Last Joined User : --------</b>
        </li>
    </ul>
  
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/User/add">Add User</a></li>
        <li><a href="<?= $this->baseUrl() ?>/User/search/delete">Delete User</a></li><!--lsaaaaaaaaaaaaa-->
        <li><a href="<?= $this->baseUrl() ?>/User/search/edit">Edit User</a></li>
        <li><a href="<?= $this->baseUrl() ?>/User/search">Search User</a></li>
        <li><a href="<?= $this->baseUrl() ?>/User/list">List Users</a></li>
        
    </ul>
</div>