<div class="row clearfix">
    <div class="col-md-8 column">
        <span class="label label-success" style="font-size: 20px">Users</span><br><br>
        <span class="label label-success" style="font-size: 15px">Users Statistics</span>
        <ul class="list-group">
            <li class="list-group-item">
              <span class="badge">14</span>
              Number of Users :
            </li>
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Joined User :
            </li>
          </ul>

        <div class="btn-group btn-group-justified">
            <a href="<?= $this->baseUrl() ?>/User/add" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/add.png" style="width: 15px;margin-right: 5px">Add User</a>
        <a href="<?= $this->baseUrl() ?>/User/search" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/search.png" style="width: 15px;margin-right: 5px">Search Users</a>
        <a href="<?= $this->baseUrl() ?>/User/list" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/list.png" style="width: 15px;margin-right: 5px">List Users</a>
        </div>
        <br><br>
        <a href="javascript:history.back();" class="btn btn-default">Back</a>    
    </div>
    <div class="col-md-2 column"></div>
</div>

