<!--<div style="height: 100%;width: 100%;background-color: #000">
<iframe align="center" width="100%" height="100%" src="<?php //echo $this->baseUrl() ?>/user/list" frameborder="yes" scrolling="yes" name="myIframe" id="myIframe"> </iframe>
<br /><br />-->
<div id="view-content">
    <h1>Users :</h1>
    <h2>Users Statistics : </h2>
    <ul>
        <li>
            <b>Number of Users : </b>
        </li>
        <li>
            <b>Last Joined User : --------</b>
        </li>
    </ul>
  
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/User/add">Add User</a></li>
     <!--   <li><a href="<?php //echo $this->baseUrl() ?>/User/search/delete/1">Delete User</a></li>
        <li><a href="<?php //echo $this->baseUrl() ?>/User/search/edit/1">Edit User</a></li>-->
        <li><a href="<?= $this->baseUrl() ?>/User/search">Search Users</a></li>
        <li><a href="<?= $this->baseUrl() ?>/User/list">List Users</a></li>
        
    </ul>
</div>