

    <table>
        <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Email</th>            
            <th>Telephone</th>
            <th>Mobile</th>
            <th>Type</th>
            <th>Date</th>
            <th>Action</th>
        </tr>

<?php 
    for($i = 0; $i < count($this->users); $i++){

        echo "<tr><td>".$this->users[$i]["name"]."</td>";
        echo "<td>";
        if ($this->users[$i]["sex"] == 'F') {
            echo "Female";
        } elseif ($this->users[$i]["sex"] == 'M') {
            echo "Male";
        }
        echo "</td>";
        echo "<td>".$this->users[$i]["email"]."</td>";
        echo "<td>".$this->users[$i]["telephone"]."</td>";
        echo "<td>".$this->users[$i]["mobile"]."</td>";
        echo "<td>".$this->users[$i]["role"]."</td>";
        echo "<td>".$this->users[$i]["join_date"]."</td>";
        echo "<td><a href='delete/userId/".$this->users[$i]['id']."'>Delete  |&nbsp;</a><a href='edit/userId/".$this->users[$i]['id']."'>  Edit</a></td>";
        echo "</tr>";       
        
    }

?>
    </table>

    <a href="javascript:history.back();">Back</a>

