<br /><br />
<div id="view-content">
	<p>View script for controller <b>User</b> and script/action name <b>list</b></p>
    <table style= 'border:1px solid black;'>
        <tr>
            <th style='border:1px solid black;'>Name</th>
            <th style='border:1px solid black;'>Gender</th>
            <th style='border:1px solid black;'>Email</th>            
            <th style='border:1px solid black;'>Telephone</th>
            <th style='border:1px solid black;'>Mobile</th>
            <th style='border:1px solid black;'>Role</th>
            <th style='border:1px solid black;'>Action</th>

        </tr>

<?php 
    for($i = 0; $i < count($this->users); $i++){
        echo "<tr><td style=' border:1px solid black;'>".$this->users[$i]["name"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->users[$i]["sex"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->users[$i]["email"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->users[$i]["telephone"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->users[$i]["mobile"]."</td>";
        echo "<td style='border:1px solid black;'>".$this->users[$i]["role"]."</td>";
        echo "<td style='border:1px solid black;'><a href='delete/userId/".$this->users[$i]['id']."'>Delete  |&nbsp;</a><a href='edit/userId/".$this->users[$i]['id']."'>  Edit</a></td>";
        echo "</tr>";       
        
    }

?>
    </table>
</div>