<style>
    .seen {
        
    }
    
    .unseen {
        border-top-style: solid;
        border-top-width: 2px;
        border-top-color: cadetblue;
        margin-top: 10px;
        background-color: beige;
    }
    
    .inline-date {
        font-size: 10px;
        color: darkgrey;
        margin-left: 55px;
        float: right;
    }
</style>

    <?php
    if($this->adminNotis) {
        echo "<table>";
        foreach($this->adminNotis as $noti){
            echo "<tr>";
            if($noti["status"]) {
                ?>
                    <td>      
                <?php
            }
            else {
                ?>
                        <td>   
                <?php
                
                
            }
            ?>
                            <img src="<?= $this->baseUrl() ?>/imgs/<?= $noti['action'] ?>Noti.png" width="22px" style="margin-right: 8px;"><a href="<?= $this->baseUrl() ?>/user/view?id=<?= $noti['user_created_id'] ?>"><?= $noti['name'] ?></a>
                    has been <?= $noti['action'] ?> a <a href="<?= $this->baseUrl() ?>/<?= $noti['table_name'] ?>/view?id=<?= $noti['record_id']?>"><?= $noti['table_name'] ?></a>
                    <font class="inline-date"><?= $noti['date']?></font>
                    </td>
            <tr>
            <?php
        }
        echo "</table>";
    }
    else if($this->phyNotis) {
        
    }
    else if($this->clinNotis) {
        
    }
    else {
        echo "No Notifications";
    }
    
    ?>
<script>
    window.onload = loadSeenNotifications();

    function loadSeenNotifications() {
        var xhr = new XMLHttpRequest();
        xhr.open("get","<?=$this->baseUrl()?>/Ajax/set-Admin-Notification-Seen");
        xhr.send();
    }
</script>
    