<style>
    .unseen {
        border-top-style: solid;
        border-top-width: 2px;
        border-top-color: cadetblue;
        margin-top: 10px;
        background-color: beige;
    }
    
    .inline-date {
        font-size: 10px;
        color: darkgrey;
        margin-left: 55px;
        float: right;
    }
</style>
<div class="row clearfix">
    <div class="col-md-6 column">
    
<hr>
              
              <h4>Notifications</h4>
              
              <div class="table-responsive">
              
    <?php
        $authorization = Zend_Auth::getInstance();
        if ($authorization->hasIdentity()) {
            $authInfo = $authorization->getIdentity();
            $userType = $authInfo['userType'];
        }

    if($this->adminNotis) {
        $noti = $this->adminNotis;

        echo "<table class='table table-hover'>";
        foreach($this->paginator as $noti){
            echo "<tr>";
            if($noti["adminStatus"]) {
                ?>
                    <td><i class="pull-right fa fa-edit"></i>
                        
                <?php
            }
            else {
                ?>  
                        <td style="background: lemonchiffon"><i class="pull-right fa fa-edit"></i>
                <?php  
            }
            ?>
                    <img src="<?= $this->baseUrl() ?>/imgs/<?= $noti['action'] ?>Noti.png" width="22px" style="margin-right: 8px;"><a href="<?= $this->baseUrl() ?>/user/view?id=<?= $noti['user_created_id'] ?>"><?= $noti['name'] ?></a>
                    has <?php if($noti['action'] == "insert")
                        echo $noti['action']."ed a ";
                    else
                        echo $noti['action']."d a ";
                    ?><a href="<?= $this->baseUrl() ?>/<?php if($noti['table_name'] == "visit_request")
                                                                echo "visit";
                                                              else 
                                                                echo $noti['table_name'];                       
                        ?>/view?id=<?= $noti['record_id']?>"><?= $noti['table_name'] ?></a>
                    <font class="inline-date"><?= $noti['date']?></font>
                    </td>
            <tr>
            <?php
        }
        echo "</table>";
        echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
    }

    else if($this->clinicNotis)
    {
        $noti = $this->clinicNotis;
        echo "<table class='table table-hover'>";
        foreach($this->paginator as $noti){
            echo "<tr>";
            if($noti["notiStatus"]) {
                ?>
                    <td><i class="pull-right fa fa-edit"></i>
                        
                <?php
            }
            else {
                ?>  
                        <td style="background: lemonchiffon"><i class="pull-right fa fa-edit"></i>
                <?php  
            }
            ?>
                    <img src="<?= $this->baseUrl() ?>/imgs/<?= $noti['notiType'] ?>Noti.png" width="22px" style="margin-right: 8px;"><a href="<?= $this->baseUrl() ?>/visit/view/id/<?= $noti['id'] ?>">Visit</a>
                    date(<?= substr($noti['created_date'],0,10) ?>) STATUS <?= ucfirst($noti['notiType']) ?>
                    </td>
            <tr>
            <?php
        }
        echo "</table>";
        echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
    }
    else if($this->physNotis){
        $noti = $this->physNotis;
        echo "<table>";
        foreach($this->paginator as $noti){
            echo "<tr>";
            if($noti["status"]) {
                ?>
                    <td> 
                        
                <?php
            }
            else {
                ?>  
                        <td style="background: lemonchiffon">
                <?php  
            }
            ?>
                            <img src="<?= $this->baseUrl() ?>/imgs/<?= $noti['action'] ?>Noti.png" width="22px" style="margin-right: 8px;"><?= $noti['action'] ?>&nbsp;Visit Request&nbsp;<a href="<?= $this->baseUrl()."/visit/view/id/".$noti["visit_id"] ?>">(Visit Details)</a>
                    </td>
            <tr>
            <?php
        }
        echo "</table>";
        echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
    }else {
        echo "No Notifications";
    }
    
    ?>
                </div>
    </div>
    <div class="col-md-6 column"></div>
</div>
<script>
    window.onload = loadSeenNotifications();

    function loadSeenNotifications() {
        var xhr = new XMLHttpRequest();
        
            if(xhr.readyState === 4) {
                alert(this.responseText);
            }
        
        userType = '<?= $userType ?>';
        if(userType != "admin") {
            userType = '-<?=    ucfirst($userType) ?>';
        }   
        xhr.open("get","<?=$this->baseUrl()?>/Ajax/set"+userType+"-Notification-Seen");
        xhr.send();
    }
</script>


    