<br /><br />
<div id="view-content">
    <div>
        <?php //echo $this->baseUrl()."/user/search/".$this->choice."/0"?>
        <form action="" method="post">
            <?php           
            echo $this->form->email."<br>";
            echo $this->form->role."<br>";
            echo $this->form->btn;
           ?>
        </form>
    </div>
    <div>
        <?php
        if($this->userData){
            echo "<table>";
            echo "<tr><th>Name</th>";
            echo "<th>Action</th></tr>";
            foreach ($this->userData as $user) {
                echo "<tr>";
                echo "<td>".$user['email']."</td>";
                echo "<td>";
                echo "<a href='". $this->baseUrl()."/user/edit/userId/".$user["id"]."'> Edit </a> - ";
                echo "<a href='". $this->baseUrl()."/user/delete/userId/".$user["id"]."'> Delete </a> - ";
                echo "<a href='". $this->baseUrl()."/user/view/userId/".$user["id"]."'> Patient Information </a>";
                echo "</td>";
                echo "</tr>";
            }
            echo "</table>";
            
        }
        ?>
        <a href="javascript:history.back();">Back</a>       
    </div>
    <div>
        <?php if($this->dataNotFound){
            echo "No matches were found";
        }?>
    </div>
</div>

