<div class="row clearfix">
    <div class="col-md-10 column">
    <?php 
    if($this->userData){ ?>
	<div class="row">
            <div class="col-sm-10">
                    <h1><?= $this->userData["name"]; ?></h1></div>
    	<div class="col-sm-2"><a href="/users" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="<?= $this->baseUrl() ?>/imgs/profile.png"></a></div>
    </div> 
    </div>
<div class="row">
                <?php if($this->physUser){ 
  		echo "<div class='col-sm-3'>";
             }else{
                    echo "<div class='col-sm-8'>";
            }?>
              
          <ul class="list-group">
            <li class="list-group-item text-muted">Profile</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Gender</strong></span> <?php if ($this->userData["sex"] == 'F') {
                                                                        echo "Female";
                                                                    } elseif ($this->userData["sex"] == 'M') {
                                                                        echo "Male";
                                                                    } ?></li>        
        
            <li class="list-group-item text-right"><span class="pull-left"><strong>E-mail</strong></span> <?= $this->userData["email"]; ?></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Account Type</strong></span> <?= $this->userData["role"]; ?></li>
<?php if($this->physUser){?>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Title</strong></span> <?= $this->physData["title"]; ?></li>            
        <li class="list-group-item text-right"><span class="pull-left"><strong>Group Name</strong></span> <?= $this->physData["group_name"]; ?></li>            
<?php }?>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Join Date</strong></span> <?= $this->userData["join_date"]; ?></li>            
                  </ul>
          <div class="panel panel-default">
            <div class="panel-heading">Contact <i class="fa fa-link fa-1x"></i></div>
            <div class="panel-body">
                <label>Telephone : </label><label><?= $this->userData["telephone"]; ?></label><br>
                <label>Mobile : </label><label><?= $this->userData["mobile"]; ?></label>
            </div>
            
          </div>                    
       
   <?php }else{
        echo "Error in loading data..";
    }
    ?>
 <?php echo "</div>"; ?><!--col 3-->
 
<?php if($this->physUser){ ?>
 <div class="col-sm-7">
          
          <ul class="nav nav-tabs" id="myTab">
                <li class="active"><a href="#accepted" data-toggle="tab">Accepted Visits</a></li>
                <li><a href="#pending" data-toggle="tab">Pending Visits</a></li>
                <li><a href="#previous" data-toggle="tab">Previous Visits</a></li>
          </ul>
            
            
              
          <div id="myTabContent" class="tab-content">

            <section id="accepted" class="tab-content active">
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                        <th>Medical Group</th>
                        <th>Physician Name</th>
                        <th>Description</th>
                        <th>Visit Date</th>
                        <th>Type</th>
                        <th>Notes</th>
                        <th>Dependency</th>
                        <th>GP</th>
                    </tr>
                  </thead>
                  <tbody id="items">
                        <?php 
                        if($this->acceptedVisits){
                            for($i = 0; $i < count($this->acceptedVisits); $i++){
                                echo "<tr><td>".$this->acceptedVisits[$i]["group_name"]."</td>";
                                echo "<td>".$this->acceptedVisits[$i]["physician"]."</td>";
                                echo "<td>".$this->acceptedVisits[$i]["description"]."</td>";
                                echo "<td>".$this->acceptedVisits[$i]["date"]."</td>";
                                echo "<td>".$this->acceptedVisits[$i]["type"]."</td>";
                                echo "<td>".$this->acceptedVisits[$i]["notes"]."</td>";
                                echo "<td>".$this->acceptedVisits[$i]["depandency"]."</td>";
                                echo "<td>".$this->acceptedVisits[$i]["gp_id"]."</td>";
                                echo "</tr>";              
                            }
                        }

                ?>
                  </tbody>
                </table>
              </div>
            </section>
            <section id="pending" class="tab-content hide">
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                        <th>Medical Group</th>
                        <th>Description</th>
                        <th>Visit Date</th>
                        <th>Type</th>
                        <th>Notes</th>
                        <th>Dependency</th>
                        <th>GP</th>
                    </tr>
                  </thead>
                  <tbody id="items">
                        <?php 
                               if($this->pendingVisits){
                                   for($i = 0; $i < count($this->pendingVisits); $i++){
                                       echo "<tr><td>".$this->pendingVisits[$i]["group_name"]."</td>";
                                       echo "<td>".$this->pendingVisits[$i]["description"]."</td>";
                                       echo "<td>".$this->pendingVisits[$i]["date"]."</td>";
                                       echo "<td>".$this->pendingVisits[$i]["type"]."</td>";
                                       echo "<td>".$this->pendingVisits[$i]["notes"]."</td>";
                                       echo "<td>".$this->pendingVisits[$i]["depandency"]."</td>";
                                       echo "<td>".$this->pendingVisits[$i]["gp_id"]."</td>";
                                       echo "</tr>";              
                                   }
                               }

                       ?>
                  </tbody>
                </table>
              </div>
            </section> 
            <section id="previous" class="tab-content hide">
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                        <th>Medical Group</th>
                        <th>Physician Name</th>
                        <th>Description</th>
                        <th>Visit Date</th>
                        <th>Type</th>
                        <th>Notes</th>
                        <th>Dependency</th>
                        <th>GP</th>
                    </tr>
                  </thead>
                  <tbody id="items">
                          <?php 
                            if($this->previousVisits){
                                for($i = 0; $i < count($this->previousVisits); $i++){
                                    echo "<tr><td>".$this->previousVisits[$i]["group_name"]."</td>";
                                    echo "<td>".$this->previousVisits[$i]["physician"]."</td>";
                                    echo "<td>".$this->previousVisits[$i]["description"]."</td>";
                                    echo "<td>".$this->previousVisits[$i]["date"]."</td>";
                                    echo "<td>".$this->previousVisits[$i]["type"]."</td>";
                                    echo "<td>".$this->previousVisits[$i]["notes"]."</td>";
                                    echo "<td>".$this->previousVisits[$i]["depandency"]."</td>";
                                    echo "<td>".$this->previousVisits[$i]["gp_id"]."</td>";
                                    echo "</tr>";              
                                }
                            }

                        ?>
                  </tbody>
                </table>
              </div>
              </section>
          </div>
               
    <br>
    <div class="btn-group btn-group-justified">
            <a href="<?= $this->baseUrl()."/Patient/update-History/id/".$this->patientId; ?>" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/add.png" style="width: 15px;margin-right: 5px">Add Medical History</a>
            <a href="<?= $this->baseUrl()."/patient/edit/patientId/".$this->patientId ?>" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/edit.png" style="width: 15px;margin-right: 5px">Edit Information</a>
            <a href="<?= $this->baseUrl() ?>/patient/delete/patientId/<?= $this->patientId ?>" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/deleteNoti.png" style="width: 15px;margin-right: 5px">Delete Patient</a>
        </div>

        </div><!--/col-7-->
        
        <?php }else{
    echo "Error in retreiving data..";
}?>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 

</div> 
</div>