<br /><br />
<div id="view-content">
	<p>View script for controller <b>Login</b> and script/action name <b>login</b></p>
        
        
        <form method="post" action="">
        <?php
        //$this->form->setAction($this->url());
        
        echo $this->form;
             echo "<a href='". $this->baseUrl()."/sign/user?id=".$checkdata['id']."'> signout </a>";
        
        ?>
        </form>
</div>