<br /><br />
<div id="view-content">
    <label><strong>Name : </strong></label><label><?= $this->userData["name"]; ?></label><br><br>
    <label><strong>Gender : </strong></label><label><?= $this->userData["sex"]; ?></label><br><br>
    <label><strong>E-mail : </strong></label><label><?= $this->userData["email"]; ?></label><br><br>
    <label><strong>Telephone : </strong></label><label><?= $this->userData["telephone"]; ?></label><br><br>
    <label><strong>Mobile : </strong></label><label><?= $this->userData["mobile"]; ?></label><br><br>
    <label><strong>Account Type : </strong></label><label><?= $this->userData["role"]; ?></label><br><br>
    <label><strong>Join Date : </strong></label><label><?= $this->userData["join_date"]; ?></label><br><br>    
</div>