<br /><br />
<div class="right_header">
    <a href="<?= $this->baseUrl() ?>/Radiation" class="logo_link">Radiations</a>
</div>
<h2>Radiations Statistics</h2>
<ul>
    <li>
        <b>Number of Radiations : <?= $this->radiationsStatistics['count'] ?></b>
    </li>
    <li>
        <b>Last Inserted Radiation : --------</b>
    </li>
    <li>
        <b>Last Updated Radiation : --------</b>
    </li>
</ul>

<ul>
    <li><a href="<?= $this->baseUrl() ?>/Radiation/add">Add Radiation</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Radiation/view">View Radiation</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Radiation/delete">Delete Radiation</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Radiation/edit">Edit Radiation</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Radiation/search">Search Radiation</a></li>
    <li><a href="<?= $this->baseUrl() ?>/Radiation/list">List Radiations</a></li>

</ul>