<div class="row clearfix">
    <div class="col-md-2 column"></div>
    <div class="col-md-8 column">
        <span class="label label-success" style="font-size: 20px">Radiations</span>
        <span class="label label-success" style="font-size: 15px">Radiations Statistics</span>
        <ul class="list-group">
            <li class="list-group-item">
              <span class="badge">14</span>
              Number of Radiations :
            </li>
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Joined Radiation :
            </li>
            <li class="list-group-item">
              <span class="badge"> --------</span>
              Last Joined Radiation :
            </li>
          </ul>

        <div class="btn-group btn-group-justified">
            <a href="<?= $this->baseUrl() ?>/Radiation/add" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/add.png" style="width: 15px;margin-right: 5px">Add Radiation</a>
            <a href="<?= $this->baseUrl() ?>/Radiation/search" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/search.png" style="width: 15px;margin-right: 5px">Search Radiations</a>
            <a href="<?= $this->baseUrl() ?>/Radiation/list" class="btn btn-default"><img src="<?= $this->baseUrl() ?>/imgs/list.png" style="width: 15px;margin-right: 5px">List Radiations</a>
        </div>
        <br><br>
        <a href="javascript:history.back();" class="btn btn-default">Back</a>    
    </div>
    <div class="col-md-2 column"></div>
</div>
