<div class="row clearfix">
    <div class="col-md-2 column"></div>
    <div class="col-md-8 column">
        <span class="label label-primary" style="font-size: 25px">Radiation List</span>
        <br><br>
        <?php
        if ($this->radiations) {
            $radiation = $this->radiations;
            echo "<table class='table table-striped table-hover'>";
            echo "<thead><tr><th>Name</th><th>Action</th></tr></thead>";
            foreach ($this->paginator as $radiation) {
                echo "<tr>";
                echo "<td>".$radiation['name']."</td>";
                echo "<td>";
                echo "<a href='". $this->baseUrl()."/Radiation/view?id=".$radiation['id']."'> View </a>";
                echo "<a href='". $this->baseUrl()."/Radiation/edit?id=".$radiation['id']."'> Edit </a>";
                echo "<a href='". $this->baseUrl()."/Radiation/delete?id=".$radiation['id']."'> Delete </a>";
                echo "</td>";
                echo "</tr>";
            }
            echo "</table>";
            echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
        }
        else {
            echo "<h2> No, Radiations !!</h2>";
            echo "but you can <a href='".$this->baseUrl()."/Radiation/add' >Add Radiation</a> ";
        }
    ?>
    <a href="javascript:history.back();" class="btn btn-default">Back</a> 
    </div>
    <div class="col-md-2 column"></div>
</div>
