<div class="row clearfix">
    <div class="col-md-6 column">
<span class="label label-primary" style="font-size: 25px">Radiation Search</span>
<br><br>
<form class="form-horizontal" method="GET">
    <fieldset>
        <legend>Search</legend>
        <div class="form-group">
          <label for="key" class="col-lg-2 control-label">Name</label>
          <div class="col-lg-10">
              <input type="text" id="key" name="key" placeholder="Enter search key" class="form-control"/>
          </div>
        </div>
        <div class="form-group">
          <div class="col-lg-10 col-lg-offset-2">
              <input type="submit" value="Search" class="btn btn-primary"/>
          </div>
        </div>
    </fieldset>
</form>
<?php
    if( $this->key ) {
        echo "<script>document.getElementById('key').value = '".$this->key."'; </script>";
        if ($this->radiations) {
            echo "<table class='table table-striped table-hover'>";
            echo "<tr><th>Name</th><th>Action</th></tr>";
            foreach ($this->radiations as $radiation) {
                echo "<tr>";
                echo "<td>".$radiation['name']."</td>";
                echo "<td>";
                echo "<a href='". $this->baseUrl()."/Radiation/view?id=".$radiation['id']."' class='btn btn-info'> View </a>";                                
                echo "<a href='". $this->baseUrl()."/Radiation/edit?id=".$radiation['id']."' class='btn btn-default'> Edit </a>";
                echo "<a href='". $this->baseUrl()."/Radiation/delete?id=".$radiation['id']."' class='btn btn-default'> Delete </a>";
                echo "</td>";
                echo "</tr>";
            }
            echo "</table>";
        }
        else {
            echo "<h2>Not Found !!</h2>";
        }
    }
?>

    </div>
    <div class="col-md-3 column"></div>
</div>

