<br /><br />
<div id="view-content">
	<p>View script for controller <b>MedicationHistory</b> and script/action name <b>add</b></p>
</div>
<form action="" method="post">
<?php
    echo $this->medicationForm->medication.
            $this->medicationForm->patient.
            $this->medicationForm->physician.
            $this->medicationForm->visit.
            $this->medicationForm->add;
?>
</form>