<form action="" method="post">
        <input type="text" name="patient" placeholder="Enter search patient .. "/>
        <input type="submit" value="Search"/>
</form>

 <?php
if ($this->medicationHistory) {
    var_dump($this->medicationHistory);
    echo "<h2>Has Data !!</h2>";
    echo "<table>";
    echo "<tr><th>patient</th>";
    echo "<th>physician</th>";
    echo "<th>medication";
    echo "<th>date</th></tr>";
    foreach ($this->medicationHistory as $medication) {
        echo "<tr>";
        echo "<td>".$medication["patient"]."</td>";
        echo "<td>".$medication["physician"]."</td>";
        echo "<td>".$medication["medication"]."</td>";
        echo "<td>".$medication["date"]."</td>";
        echo "<td>";
        echo "<a href='". $this->baseUrl()."/medication-history/view?id=".$medication["medHisID"]."'> View </a>";
        echo "<a href='". $this->baseUrl()."/medication-history/edit?id=".$medication["medHisID"]."'> Edit </a>";
        echo "<a href='". $this->baseUrl()."/medication-history/delete?id=".$medication["medHisID"]."'> Delete </a>";
        echo "</td>";
        echo "</tr>";
    }
    echo "</table>";
}
else {
    echo "<h2>Not Found !!</h2>";
}   
?>