<link href="<?= $this->baseUrl() ?>/css/tableStyle.css" rel="stylesheet">
<form action="" method="post">
        <input type="text" name="patient" placeholder="Enter search patient .. "/>
        <input type="submit" value="Search"/>
</form>

 <?php
if ($this->diseaseHistory) {
    echo "<table>";
    echo "<tr><th>patient</th>";
    echo "<th>disease";
    echo "<th>date</th></tr>";
    foreach ($this->diseaseHistory as $disease) {
        echo "<tr>";
        echo "<td>".$disease["patient"]."</td>";
        echo "<td>".$disease["disease"]."</td>";
        echo "<td>".$disease["date"]."</td>";
        echo "<td>";
        echo "<a href='". $this->baseUrl()."/diseasehistory/edit?id=".$disease["disHisID"]."'> Edit </a>";
        echo "<a href='". $this->baseUrl()."/diseasehistory/delete?id=".$disease["disHisID"]."'> Delete </a>";
        echo "</td>";
        echo "</tr>";
    }
    echo "</table>";
}
else {
    echo "<h2>Not Found !!</h2>";
}   
?>